/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FPE2;

import javax.swing.JOptionPane;

/**
 *
 * @author ROBLES
 */
public class Insert_Edit_Customer extends javax.swing.JFrame {
    String choose = "";
    /**
     * Creates new form AddSupplier
     */
    public Insert_Edit_Customer() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        KG2_ADD_STOCK_GENSET = new keeptoo.KGradientPanel();
        jPanel2 = new javax.swing.JPanel();
        add_edit_customer = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cus_name = new javax.swing.JTextField();
        cus_address = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cus_contact = new javax.swing.JTextField();
        cus_email = new javax.swing.JTextField();
        id_customer = new javax.swing.JLabel();
        id_edit_customer = new javax.swing.JLabel();
        addBox_item = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        CUSTOMER_MENU = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        KG2_ADD_STOCK_GENSET.setkEndColor(new java.awt.Color(153, 204, 255));
        KG2_ADD_STOCK_GENSET.setkGradientFocus(700);
        KG2_ADD_STOCK_GENSET.setkStartColor(new java.awt.Color(0, 255, 153));
        KG2_ADD_STOCK_GENSET.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add_edit_customer.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        add_edit_customer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add_edit_customer.setText("ADD");
        add_edit_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_edit_customerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(add_edit_customer, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(add_edit_customer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        KG2_ADD_STOCK_GENSET.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 190, 50));

        back.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("BACK");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        KG2_ADD_STOCK_GENSET.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 190, 50));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel17.setText("NAME");
        jLabel17.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 100, 26));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel16.setText("ADDRESS");
        jLabel16.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 100, 26));

        cus_name.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        cus_name.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(cus_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 280, 31));

        cus_address.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        cus_address.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(cus_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 280, 31));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel19.setText("EMAIL ");
        jLabel19.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 100, 26));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel18.setText("CONTACT");
        jLabel18.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 100, 26));

        cus_contact.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        cus_contact.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(cus_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 280, 31));

        cus_email.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        cus_email.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(cus_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 280, 31));

        id_customer.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        id_customer.setText("ID");
        id_customer.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(id_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 100, 26));

        id_edit_customer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        id_edit_customer.setText("NONE");
        KG2_ADD_STOCK_GENSET.add(id_edit_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 280, 30));

        addBox_item.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addBox_item.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CUSTOMER", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 20))); // NOI18N
        addBox_item.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        KG2_ADD_STOCK_GENSET.add(addBox_item, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 1010, 350));

        getContentPane().add(KG2_ADD_STOCK_GENSET, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1080, 625));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        CUSTOMER_MENU.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        CUSTOMER_MENU.setForeground(new java.awt.Color(255, 255, 255));
        CUSTOMER_MENU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CUSTOMER_MENU.setText("ADD CUSTOMER");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(315, Short.MAX_VALUE)
                    .addComponent(CUSTOMER_MENU, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(400, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(15, Short.MAX_VALUE)
                    .addComponent(CUSTOMER_MENU, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked

        // back ADD FILTER / PART
        dispose();
        this.dispose();
        Mainpage.edit_cus_id.setText("ID");
        Mainpage.edit_cus_name.setText("NAME");
        Mainpage.edit_cus_address.setText("ADDRESS");
        Mainpage.edit_cus_email.setText("EMAIL");
        Mainpage.edit_cus_contact.setText("CONTACT");
    }//GEN-LAST:event_backMouseClicked

    private void add_edit_customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_edit_customerMouseClicked
        // TODO add your handling code here:
        choose = "ADD CUSTOMER";
        String cus_menu = CUSTOMER_MENU.getText();
        String name,address,email,contact,id;
        name = cus_name.getText();
        address = cus_address.getText();
        email = cus_email.getText();
        contact = cus_contact.getText();
        id = id_edit_customer.getText();
        Class_Customer cc = new Class_Customer();
            if(cus_menu.equals(choose)){
                //JOptionPane.showMessageDialog(null, "ADD CUSTOMER","",JOptionPane.INFORMATION_MESSAGE);
                cc.AddCustomer(name, address, email, contact);
            }else{
                choose = "EDIT CUSTOMER";
                    if(cus_menu.equals(choose)){
                       //JOptionPane.showMessageDialog(null, "EDIT CUSTOMER","",JOptionPane.INFORMATION_MESSAGE);
                       cc.EditCustomer(name, address, email, contact, id);
                    }
            }
    }//GEN-LAST:event_add_edit_customerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insert_Edit_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insert_Edit_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insert_Edit_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insert_Edit_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insert_Edit_Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel CUSTOMER_MENU;
    private keeptoo.KGradientPanel KG2_ADD_STOCK_GENSET;
    private javax.swing.JLabel addBox_item;
    public static javax.swing.JLabel add_edit_customer;
    private javax.swing.JLabel back;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JTextField cus_address;
    public static javax.swing.JTextField cus_contact;
    public static javax.swing.JTextField cus_email;
    public static javax.swing.JTextField cus_name;
    public static javax.swing.JLabel id_customer;
    public static javax.swing.JLabel id_edit_customer;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
