/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FPE.folder;

import FPE.Class_tables;
import FPE.FPE_DB;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author Javinez
 */
public class AddCart extends javax.swing.JFrame {
   Class_tables ct = new Class_tables();
    /**
     * Creates new form AddCart
     */
    public AddCart() {
        initComponents();
        ct.ShowCart();
        Path.setVisible(false);
        quantity.setVisible(false);
        brand.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        displays = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        Cart_id = new javax.swing.JLabel();
        Path = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cart_table = new javax.swing.JTable();
        update_panel_supplier = new javax.swing.JPanel();
        Back1 = new javax.swing.JLabel();
        delete_panel_supplier = new javax.swing.JPanel();
        sup_del = new javax.swing.JLabel();
        back_panel_supplier = new javax.swing.JPanel();
        Back = new javax.swing.JLabel();
        Supplier_Search = new javax.swing.JTextField();
        quantity = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        brand = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(2, 51, 74));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displays.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        displays.setForeground(new java.awt.Color(255, 255, 255));
        displays.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displays.setText("CART LIST");
        displays.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                displaysAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel4.add(displays, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 570, 80));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 100));

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        kGradientPanel1.setkEndColor(new java.awt.Color(42, 142, 142));
        kGradientPanel1.setkStartColor(new java.awt.Color(42, 142, 142));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        kGradientPanel1.add(Cart_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 120, 30));

        Path.setText("1");
        kGradientPanel1.add(Path, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 30, 20));

        Cart_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Cart_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cart_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Cart_table);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 78, 980, 420));

        update_panel_supplier.setBackground(new java.awt.Color(0, 102, 255));
        update_panel_supplier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 246, 26)));
        update_panel_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_panel_supplierMouseClicked(evt);
            }
        });

        Back1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Back1.setForeground(new java.awt.Color(255, 255, 255));
        Back1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Btn/Btn_Process.png"))); // NOI18N
        Back1.setText(" PROCESS");
        Back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Back1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Back1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Back1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout update_panel_supplierLayout = new javax.swing.GroupLayout(update_panel_supplier);
        update_panel_supplier.setLayout(update_panel_supplierLayout);
        update_panel_supplierLayout.setHorizontalGroup(
            update_panel_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Back1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
        );
        update_panel_supplierLayout.setVerticalGroup(
            update_panel_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Back1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        kGradientPanel1.add(update_panel_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 210, 50));

        delete_panel_supplier.setBackground(new java.awt.Color(255, 77, 77));
        delete_panel_supplier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 246, 26)));

        sup_del.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        sup_del.setForeground(new java.awt.Color(255, 255, 255));
        sup_del.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sup_del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Btn/Btn_Cancel.png"))); // NOI18N
        sup_del.setText(" REMOVE");
        sup_del.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sup_delMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sup_delMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sup_delMouseExited(evt);
            }
        });

        javax.swing.GroupLayout delete_panel_supplierLayout = new javax.swing.GroupLayout(delete_panel_supplier);
        delete_panel_supplier.setLayout(delete_panel_supplierLayout);
        delete_panel_supplierLayout.setHorizontalGroup(
            delete_panel_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sup_del, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
        );
        delete_panel_supplierLayout.setVerticalGroup(
            delete_panel_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sup_del, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        kGradientPanel1.add(delete_panel_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, 210, 50));

        back_panel_supplier.setBackground(new java.awt.Color(255, 173, 51));
        back_panel_supplier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 246, 26)));

        Back.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Btn/Btn_Backs.png"))); // NOI18N
        Back.setText("BACK");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackMouseExited(evt);
            }
        });

        javax.swing.GroupLayout back_panel_supplierLayout = new javax.swing.GroupLayout(back_panel_supplier);
        back_panel_supplier.setLayout(back_panel_supplierLayout);
        back_panel_supplierLayout.setHorizontalGroup(
            back_panel_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
        );
        back_panel_supplierLayout.setVerticalGroup(
            back_panel_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        kGradientPanel1.add(back_panel_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 210, 50));

        Supplier_Search.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Supplier_Search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Supplier_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Supplier_SearchKeyPressed(evt);
            }
        });
        kGradientPanel1.add(Supplier_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 220, 35));
        kGradientPanel1.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 40, 20));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Btn/Btn_Search.png"))); // NOI18N
        kGradientPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 35, 35));
        kGradientPanel1.add(brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 100, 20));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 110, 1060, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void displaysAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_displaysAncestorAdded

    }//GEN-LAST:event_displaysAncestorAdded

    private void Cart_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cart_tableMouseClicked
        int i=Cart_table.getSelectedRow();
        TableModel model = Cart_table.getModel();
        Cart_id.setText(model.getValueAt(i,0).toString());
        brand.setText(model.getValueAt(i,1).toString());
        quantity.setText(model.getValueAt(i,4).toString());
        
    }//GEN-LAST:event_Cart_tableMouseClicked

    private void sup_delMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sup_delMouseClicked
        PreparedStatement ps;
        ResultSet rs;
        String id = Cart_id.getText();
        String brand1 = brand.getText();
        String quantity1 = quantity.getText();
        if(!Class_Cart.Cart_Item_Delete(id)){
           // JOptionPane.showMessageDialog(null, "SUCEESSFULY REMOVED");
           if(brand1.equals("") || quantity1.equals("") ){
               //nothing
           }else{
               try{
                ps=FPE_DB.getConnection().prepareStatement("SELECT `BRAND`, `QUANTITY` FROM `filter_table` WHERE `BRAND`='"+brand1+"'");
                rs = ps.executeQuery();
                if(rs.next()){
                    String findBrand = rs.getString("BRAND");
                    String findQuantity = rs.getString("QUANTITY");
                    int result = Integer.parseInt(quantity1) + Integer.parseInt(findQuantity);
                    String stringToQuantity = Integer.toString(result);
                  if(!Class_Filter.brandQuantity(findBrand, stringToQuantity)){
                      JOptionPane.showMessageDialog(null, "REMOVED SUCCESSFULLY");
                      ct.ShowCart();
                  }
                }

               }
               catch(Exception e){
                   
               }
           }
        }

    }//GEN-LAST:event_sup_delMouseClicked

    private void sup_delMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sup_delMouseEntered
    delete_panel_supplier.setBackground(new Color(255,97,97));
    }//GEN-LAST:event_sup_delMouseEntered

    private void sup_delMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sup_delMouseExited
    delete_panel_supplier.setBackground(new Color(255,77,77)); 
    }//GEN-LAST:event_sup_delMouseExited

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
       dispose();
    }//GEN-LAST:event_BackMouseClicked

    private void BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseEntered
    back_panel_supplier.setBackground(new Color(255,193,71));
    }//GEN-LAST:event_BackMouseEntered

    private void BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseExited
    back_panel_supplier.setBackground(new Color(255,173,51));  
    }//GEN-LAST:event_BackMouseExited

    private void Supplier_SearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Supplier_SearchKeyPressed
//        DefaultTableModel tm = (DefaultTableModel)Supplier_table.getModel();
//        String find = Supplier_Search.getText().toUpperCase();
//        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(tm);
//        Supplier_table.setRowSorter(tr);
//        tr.setRowFilter(RowFilter.regexFilter(find));
    }//GEN-LAST:event_Supplier_SearchKeyPressed

    private void Back1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back1MouseClicked
        String unique = "1";
        
        Process_Filter pf = new Process_Filter();
        
        pf.setVisible(true);
        dispose();
    }//GEN-LAST:event_Back1MouseClicked

    private void Back1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back1MouseEntered
        // TODO add your handling code here:
        update_panel_supplier.setBackground(new Color(0,122,245));
    }//GEN-LAST:event_Back1MouseEntered

    private void Back1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back1MouseExited
        // TODO add your handling code here: [0,102,255]
        update_panel_supplier.setBackground(new Color(0,102,255));
    }//GEN-LAST:event_Back1MouseExited

    private void update_panel_supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_panel_supplierMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_update_panel_supplierMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Back;
    public static javax.swing.JLabel Back1;
    public static javax.swing.JLabel Cart_id;
    public static javax.swing.JTable Cart_table;
    public static javax.swing.JLabel Path;
    private javax.swing.JTextField Supplier_Search;
    public static javax.swing.JPanel back_panel_supplier;
    private javax.swing.JLabel brand;
    public static javax.swing.JPanel delete_panel_supplier;
    public static javax.swing.JLabel displays;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel quantity;
    public static javax.swing.JLabel sup_del;
    public static javax.swing.JPanel update_panel_supplier;
    // End of variables declaration//GEN-END:variables
}
