/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FPE;



import static FPE.Sale_Stock.sale_Generator_Banner;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Javinez
 */
public class AddCart extends javax.swing.JFrame {
   Class_tables ct = new Class_tables();
   String getCart = null;
    /**
     * Creates new form AddCart
     */
    public AddCart() {
        initComponents();
        add_cart();
        
    }

    private void add_cart(){
        try{
        PreparedStatement ps = FPE_DB.getConnection().prepareStatement("SELECT `DATE RELEASE`, `CATEGORY`, CONCAT(`BRAND`, ' ' ,`MODEL`,' ',`KVA`,' ',`PHASING`) AS `DESCRIPTION`, `TYPE`, FORMAT(`SELLER PRICE`, '#,##0.00') AS `PRICE`, `ENGINE S N`, `ALTERNATOR S N`, `QUANTITY` FROM `add_cart`");
        ResultSet rs = ps.executeQuery();
        Cart_table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
              //System.out.println(e);
        }
    }
    
    public String getSelectedOption() {
            Enumeration<AbstractButton> radioButtons = cash_checked.getElements();
            while (radioButtons.hasMoreElements()) {
                AbstractButton currentRadioButton = radioButtons.nextElement();
                if (currentRadioButton.isSelected()) {
                    return currentRadioButton.getText();
                }
            }
            return null;
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cash_checked = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        displays = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cart_table = new javax.swing.JTable();
        update_panel_supplier = new javax.swing.JPanel();
        process = new javax.swing.JLabel();
        Supplier_Search = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        cart_customer_name = new javax.swing.JTextField();
        cart_customer_id = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        cart_amount = new javax.swing.JTextField();
        cart_balanced = new javax.swing.JTextField();
        cart_or_no = new javax.swing.JTextField();
        cart_remark = new javax.swing.JTextField();
        checked = new javax.swing.JRadioButton();
        cash = new javax.swing.JRadioButton();
        jTextField14 = new javax.swing.JTextField();
        cart_bank = new javax.swing.JTextField();
        Stock_Genset_Panel_Add6 = new javax.swing.JPanel();
        Shop_Add4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(2, 51, 74));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displays.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        displays.setForeground(new java.awt.Color(255, 255, 255));
        displays.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displays.setText("CART LIST");
        displays.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                displaysAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel4.add(displays, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 570, 80));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 100));

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        kGradientPanel1.setkEndColor(new java.awt.Color(42, 142, 142));
        kGradientPanel1.setkStartColor(new java.awt.Color(42, 142, 142));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cart_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Cart_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cart_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Cart_table);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 78, 990, 250));

        update_panel_supplier.setBackground(new java.awt.Color(0, 102, 255));
        update_panel_supplier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 246, 26)));
        update_panel_supplier.setPreferredSize(new java.awt.Dimension(170, 45));
        update_panel_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_panel_supplierMouseClicked(evt);
            }
        });

        process.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        process.setForeground(new java.awt.Color(255, 255, 255));
        process.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        process.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Btn/Btn_Process.png"))); // NOI18N
        process.setText(" PROCESS");
        process.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                processMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                processMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                processMouseExited(evt);
            }
        });

        javax.swing.GroupLayout update_panel_supplierLayout = new javax.swing.GroupLayout(update_panel_supplier);
        update_panel_supplier.setLayout(update_panel_supplierLayout);
        update_panel_supplierLayout.setHorizontalGroup(
            update_panel_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(update_panel_supplierLayout.createSequentialGroup()
                .addComponent(process, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );
        update_panel_supplierLayout.setVerticalGroup(
            update_panel_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(process, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        kGradientPanel1.add(update_panel_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, 210, 50));

        Supplier_Search.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Supplier_Search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Supplier_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Supplier_SearchKeyPressed(evt);
            }
        });
        kGradientPanel1.add(Supplier_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 220, 35));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Btn/Btn_Search.png"))); // NOI18N
        kGradientPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 35, 35));

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CUSTOMER LIST");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 190, 30));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 153));
        jTextField1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextField1.setText("CUSTOMER NAME:");
        kGradientPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 130, 30));

        cart_customer_name.setEditable(false);
        cart_customer_name.setBackground(new java.awt.Color(204, 204, 204));
        kGradientPanel1.add(cart_customer_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 160, 30));

        cart_customer_id.setEditable(false);
        cart_customer_id.setBackground(new java.awt.Color(204, 204, 204));
        kGradientPanel1.add(cart_customer_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 160, 30));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 255, 153));
        jTextField5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextField5.setText("CUSTOMER ID:");
        kGradientPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 130, 30));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(255, 255, 153));
        jTextField6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextField6.setText("BALANCED :");
        kGradientPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 130, 30));

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(255, 255, 153));
        jTextField7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextField7.setText("CASH / CHECK NO :");
        kGradientPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 130, 30));

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(255, 255, 153));
        jTextField8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextField8.setText("OR NO :");
        kGradientPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 430, 130, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("PAYMENT DETAILS :");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 120, 30));

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(255, 255, 153));
        jTextField9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextField9.setText("AMOUNT :");
        kGradientPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 130, 30));

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(255, 255, 153));
        jTextField10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextField10.setText("REMARKS :");
        kGradientPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 480, 130, 30));
        kGradientPanel1.add(cart_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 160, 30));
        kGradientPanel1.add(cart_balanced, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 160, 30));
        kGradientPanel1.add(cart_or_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, 160, 30));
        kGradientPanel1.add(cart_remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, 160, 30));

        cash_checked.add(checked);
        checked.setText("CHECKED");
        kGradientPanel1.add(checked, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 90, 30));

        cash_checked.add(cash);
        cash.setText("CASH");
        kGradientPanel1.add(cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, 60, 30));

        jTextField14.setEditable(false);
        jTextField14.setBackground(new java.awt.Color(255, 255, 153));
        jTextField14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextField14.setText("BANKED :");
        kGradientPanel1.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 130, 30));
        kGradientPanel1.add(cart_bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, 160, 30));

        Stock_Genset_Panel_Add6.setBackground(new java.awt.Color(204, 204, 255));

        Shop_Add4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Shop_Add4.setForeground(new java.awt.Color(98, 71, 73));
        Shop_Add4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Shop_Add4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Btn/arrow_35px.png"))); // NOI18N
        Shop_Add4.setText(" BACK");
        Shop_Add4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Shop_Add4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Shop_Add4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Shop_Add4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout Stock_Genset_Panel_Add6Layout = new javax.swing.GroupLayout(Stock_Genset_Panel_Add6);
        Stock_Genset_Panel_Add6.setLayout(Stock_Genset_Panel_Add6Layout);
        Stock_Genset_Panel_Add6Layout.setHorizontalGroup(
            Stock_Genset_Panel_Add6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Shop_Add4, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        Stock_Genset_Panel_Add6Layout.setVerticalGroup(
            Stock_Genset_Panel_Add6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Shop_Add4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        kGradientPanel1.add(Stock_Genset_Panel_Add6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, 170, 50));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1060, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void displaysAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_displaysAncestorAdded
        String Banner = displays.getText();
    
            if(Banner.equals("CART LIST"))
            {
                try{
                    PreparedStatement ps=FPE_DB.getConnection().prepareStatement("SELECT `PROCESS` FROM `add_cart` ORDER BY `PROCESS` DESC LIMIT 1");
                    ResultSet rs = ps.executeQuery();
                    if(rs.next()){
                        getCart = rs.getString("PROCESS");
                    }
                }
                catch(Exception e){
                    e.printStackTrace();
                }
            }
    }//GEN-LAST:event_displaysAncestorAdded

    private void Cart_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cart_tableMouseClicked
        int i=Cart_table.getSelectedRow();
        TableModel model = Cart_table.getModel();
//        Cart_id.setText(model.getValueAt(i,0).toString());
//        brand.setText(model.getValueAt(i,1).toString());
//        quantity.setText(model.getValueAt(i,4).toString());
        
    }//GEN-LAST:event_Cart_tableMouseClicked

    private void Supplier_SearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Supplier_SearchKeyPressed
//        DefaultTableModel tm = (DefaultTableModel)Supplier_table.getModel();
//        String find = Supplier_Search.getText().toUpperCase();
//        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(tm);
//        Supplier_table.setRowSorter(tr);
//        tr.setRowFilter(RowFilter.regexFilter(find));
    }//GEN-LAST:event_Supplier_SearchKeyPressed

    private void processMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_processMouseClicked
        try{
            String selected = getSelectedOption();
            Class_Process cp = new Class_Process();
            String customer_id = "";
            String amount = "";
            String balanced = "";
            String cash_checked = "";
            String bank = "";
            String or_no = "";
            String remark = "";
            String status = "DONE";
                PreparedStatement ps=FPE_DB.getConnection().prepareStatement("SELECT `PROCESS` FROM `add_cart` ORDER BY `PROCESS` DESC LIMIT 1");
                ResultSet rs = ps.executeQuery();
                if(rs.next()){
                    getCart = rs.getString("PROCESS");
                       
                if (selected == null) {
                    JOptionPane.showMessageDialog(null, "CHOOSE CASH OR CHECKED");
                    return;
                }
                
                switch (selected.toUpperCase()) {
                    case "CASH":
                        cash_checked = "CASH";
                        break;
                    case "CHECKED":
                        cash_checked = "CHECKED";
                        break;
                }

                    // getText
                    amount = cart_amount.getText();
                    balanced = cart_balanced.getText();
                    bank = cart_bank.getText();
                    or_no = cart_or_no.getText();
                    remark = cart_remark.getText();
                    if(!cp.process_genset_summaryStock(customer_id, amount, balanced, cash_checked, bank, or_no, remark, status,getCart) && !cp.process_genset_addCart(status, getCart) && !cp.process_cart_delete()){
                        JOptionPane.showMessageDialog(null, "TRANSACTION HAS PROCESSED","",JOptionPane.INFORMATION_MESSAGE);
                        add_cart();
                        ct.Cart_Generator();
                        ct.Generator();
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "EMPTY CART! ","",JOptionPane.ERROR_MESSAGE);
                    add_cart();
                    ct.Cart_Generator();
                    ct.Generator();
                }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_processMouseClicked

    private void processMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_processMouseEntered
        // TODO add your handling code here:
        update_panel_supplier.setBackground(new Color(0,122,245));
    }//GEN-LAST:event_processMouseEntered

    private void processMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_processMouseExited
        // TODO add your handling code here: [0,102,255]
        update_panel_supplier.setBackground(new Color(0,102,255));
    }//GEN-LAST:event_processMouseExited

    private void update_panel_supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_panel_supplierMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_update_panel_supplierMouseClicked

    private void Shop_Add4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Shop_Add4MouseClicked
        dispose();
    }//GEN-LAST:event_Shop_Add4MouseClicked

    private void Shop_Add4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Shop_Add4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Shop_Add4MouseEntered

    private void Shop_Add4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Shop_Add4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Shop_Add4MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Table_Customer tcs = new Table_Customer();
        Table_Customer.id_cus = null;
        tcs.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Cart_table;
    public static javax.swing.JLabel Shop_Add4;
    public static javax.swing.JPanel Stock_Genset_Panel_Add6;
    private javax.swing.JTextField Supplier_Search;
    private javax.swing.JTextField cart_amount;
    private javax.swing.JTextField cart_balanced;
    private javax.swing.JTextField cart_bank;
    public static javax.swing.JTextField cart_customer_id;
    public static javax.swing.JTextField cart_customer_name;
    private javax.swing.JTextField cart_or_no;
    private javax.swing.JTextField cart_remark;
    private javax.swing.JRadioButton cash;
    private javax.swing.ButtonGroup cash_checked;
    private javax.swing.JRadioButton checked;
    public static javax.swing.JLabel displays;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private keeptoo.KGradientPanel kGradientPanel1;
    public static javax.swing.JLabel process;
    public static javax.swing.JPanel update_panel_supplier;
    // End of variables declaration//GEN-END:variables
}
