/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FPE;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Robles
 */
public class AddFullout extends javax.swing.JFrame {

    int process = 1;
    public static String srs_nos = "";
    public AddFullout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        displays = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        Stock_Genset_Panel_Back = new javax.swing.JPanel();
        Stock_Genset_Back = new javax.swing.JLabel();
        Stock_Genset_Panel_Update = new javax.swing.JPanel();
        Stock_Genset_Update = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        srs_no = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        encode = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        store_keeper = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        purpose = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        approve = new javax.swing.JTextField();
        date = new datechooser.beans.DateChooserCombo();
        account_charge = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(2, 51, 74));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displays.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        displays.setForeground(new java.awt.Color(255, 255, 255));
        displays.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displays.setText("REQUESITION SLIP");
        displays.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                displaysAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel4.add(displays, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 490, 80));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 100));

        kGradientPanel1.setkEndColor(new java.awt.Color(42, 142, 142));
        kGradientPanel1.setkStartColor(new java.awt.Color(42, 142, 142));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Stock_Genset_Panel_Back.setBackground(new java.awt.Color(185, 144, 149));

        Stock_Genset_Back.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        Stock_Genset_Back.setForeground(new java.awt.Color(255, 255, 255));
        Stock_Genset_Back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Stock_Genset_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Btn/arrow_35px.png"))); // NOI18N
        Stock_Genset_Back.setText(" BACK");
        Stock_Genset_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Stock_Genset_BackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Stock_Genset_BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Stock_Genset_BackMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Stock_Genset_Panel_BackLayout = new javax.swing.GroupLayout(Stock_Genset_Panel_Back);
        Stock_Genset_Panel_Back.setLayout(Stock_Genset_Panel_BackLayout);
        Stock_Genset_Panel_BackLayout.setHorizontalGroup(
            Stock_Genset_Panel_BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Stock_Genset_Panel_BackLayout.createSequentialGroup()
                .addComponent(Stock_Genset_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );
        Stock_Genset_Panel_BackLayout.setVerticalGroup(
            Stock_Genset_Panel_BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Stock_Genset_Back, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        kGradientPanel1.add(Stock_Genset_Panel_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 170, -1));

        Stock_Genset_Panel_Update.setBackground(new java.awt.Color(0, 163, 204));

        Stock_Genset_Update.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        Stock_Genset_Update.setForeground(new java.awt.Color(255, 255, 255));
        Stock_Genset_Update.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Stock_Genset_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Select/save_33px.png"))); // NOI18N
        Stock_Genset_Update.setText(" SAVE");
        Stock_Genset_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Stock_Genset_UpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Stock_Genset_UpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Stock_Genset_UpdateMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Stock_Genset_Panel_UpdateLayout = new javax.swing.GroupLayout(Stock_Genset_Panel_Update);
        Stock_Genset_Panel_Update.setLayout(Stock_Genset_Panel_UpdateLayout);
        Stock_Genset_Panel_UpdateLayout.setHorizontalGroup(
            Stock_Genset_Panel_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Stock_Genset_Update, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        Stock_Genset_Panel_UpdateLayout.setVerticalGroup(
            Stock_Genset_Panel_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Stock_Genset_Update, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        kGradientPanel1.add(Stock_Genset_Panel_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 170, -1));

        name.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kGradientPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 240, 35));

        jTextField15.setEditable(false);
        jTextField15.setBackground(new java.awt.Color(255, 191, 134));
        jTextField15.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextField15.setText(" DATE :");
        jTextField15.setBorder(null);
        kGradientPanel1.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 60, 35));

        jTextField16.setEditable(false);
        jTextField16.setBackground(new java.awt.Color(255, 191, 134));
        jTextField16.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextField16.setText(" NAME :");
        jTextField16.setBorder(null);
        kGradientPanel1.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 90, 35));

        jTextField17.setEditable(false);
        jTextField17.setBackground(new java.awt.Color(255, 191, 134));
        jTextField17.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextField17.setText(" SRS NO :");
        jTextField17.setBorder(null);
        kGradientPanel1.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 70, 35));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel1.setText(" REQUESITION BY ");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 160, 35));

        srs_no.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        srs_no.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kGradientPanel1.add(srs_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 90, 35));

        jTextField18.setEditable(false);
        jTextField18.setBackground(new java.awt.Color(255, 191, 134));
        jTextField18.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextField18.setText(" MANAGER :");
        jTextField18.setBorder(null);
        kGradientPanel1.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 90, 35));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel2.setText(" APPRROVE BY");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 160, 35));

        encode.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        encode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kGradientPanel1.add(encode, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 210, 35));

        jTextField19.setEditable(false);
        jTextField19.setBackground(new java.awt.Color(255, 191, 134));
        jTextField19.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextField19.setText(" ENCODE BY :");
        jTextField19.setBorder(null);
        kGradientPanel1.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 130, 35));

        store_keeper.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        store_keeper.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kGradientPanel1.add(store_keeper, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 210, 35));

        jTextField20.setEditable(false);
        jTextField20.setBackground(new java.awt.Color(255, 191, 134));
        jTextField20.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextField20.setText(" STORE KEEPER");
        jTextField20.setBorder(null);
        kGradientPanel1.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 130, 35));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel5.setText(" ISSUE BY");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 160, 35));

        purpose.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        purpose.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kGradientPanel1.add(purpose, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 570, 35));

        jTextField21.setEditable(false);
        jTextField21.setBackground(new java.awt.Color(255, 191, 134));
        jTextField21.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextField21.setText(" PURPOSE :");
        jTextField21.setBorder(null);
        kGradientPanel1.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 120, 35));

        approve.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        approve.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kGradientPanel1.add(approve, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 240, 35));

        date.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    date.setCalendarPreferredSize(new java.awt.Dimension(500, 400));
    date.setWeekStyle(datechooser.view.WeekDaysStyle.FULL);
    date.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 14));
    date.setNavigateFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 14));
    date.setCurrentNavigateIndex(0);
    kGradientPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 90, 35));

    account_charge.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    account_charge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    kGradientPanel1.add(account_charge, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 180, 35));

    jTextField22.setEditable(false);
    jTextField22.setBackground(new java.awt.Color(255, 191, 134));
    jTextField22.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
    jTextField22.setText(" ACCOUNT CHARGE");
    jTextField22.setBorder(null);
    kGradientPanel1.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 150, 35));

    jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 153)), " REQUESITOR INFO ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 0, 20), new java.awt.Color(51, 51, 51))); // NOI18N
    kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 730, 320));

    getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 770, 410));

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void displaysAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_displaysAncestorAdded
    PreparedStatement ps;
    ResultSet rs;
    String Banner = displays.getText();

    if(Banner.equals("REQUESITION SLIP"))
    {
        try
        {
            ps=FPE_DB.getConnection().prepareStatement("SELECT `PROCESS` FROM `fullout` ORDER BY `PROCESS` DESC LIMIT 1");
            rs = ps.executeQuery();
            if(rs.next())
            {
                process = rs.getInt("PROCESS"); 
                System.out.println(""+process);
            }
        }
        catch(Exception e)
            {
                e.printStackTrace();
            }
    }
    }//GEN-LAST:event_displaysAncestorAdded

    private void Stock_Genset_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stock_Genset_BackMouseClicked
        dispose();
        
    }//GEN-LAST:event_Stock_Genset_BackMouseClicked

    private void Stock_Genset_BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stock_Genset_BackMouseEntered

        Stock_Genset_Panel_Back.setBackground(new Color(163, 235, 177));
        Stock_Genset_Back.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_Stock_Genset_BackMouseEntered

    private void Stock_Genset_BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stock_Genset_BackMouseExited
        Stock_Genset_Panel_Back.setBackground(new Color(185,144,149));
        Stock_Genset_Back.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_Stock_Genset_BackMouseExited

    private void Stock_Genset_UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stock_Genset_UpdateMouseClicked
 
        srs_nos = srs_no.getText();
        String names = name.getText(); 
        String dates = date.getText();
        String store_keepers = store_keeper.getText();
        String purposes = purpose.getText();
        String approves = approve.getText();
        String encodes = encode.getText();
        String account_charges= account_charge.getText(); 
        
        
        if(!Class_Request.Request(srs_nos, names, dates, store_keepers, purposes, approves, encodes, account_charges)  && !Class_Request.Request_Update_History(dates, srs_nos,""+process) && !Class_fullout.Fullout_Delete())
        {
            JOptionPane.showMessageDialog(null, " TRANSACTION SUCCESS !! ","",JOptionPane.UNDEFINED_CONDITION); Webpage.ct.request(); Webpage.ct.Fullout(); Webpage.ct.History();
            Print_Reciept_Request prr = new Print_Reciept_Request();
            prr.setVisible(true);
        }

    }//GEN-LAST:event_Stock_Genset_UpdateMouseClicked

    private void Stock_Genset_UpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stock_Genset_UpdateMouseEntered
        Stock_Genset_Panel_Update.setBackground(new Color(163, 235, 177));
        Stock_Genset_Update.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_Stock_Genset_UpdateMouseEntered

    private void Stock_Genset_UpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stock_Genset_UpdateMouseExited
        Stock_Genset_Panel_Update.setBackground(new Color(0,163,204));
        Stock_Genset_Update.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_Stock_Genset_UpdateMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFullout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFullout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFullout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFullout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFullout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Stock_Genset_Back;
    public static javax.swing.JPanel Stock_Genset_Panel_Back;
    public static javax.swing.JPanel Stock_Genset_Panel_Update;
    private javax.swing.JLabel Stock_Genset_Update;
    private javax.swing.JTextField account_charge;
    private javax.swing.JTextField approve;
    public static datechooser.beans.DateChooserCombo date;
    public static javax.swing.JLabel displays;
    private javax.swing.JTextField encode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField purpose;
    private javax.swing.JTextField srs_no;
    private javax.swing.JTextField store_keeper;
    // End of variables declaration//GEN-END:variables
}
