/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FPE;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Robles
 */
public class Print_Reciept_Parts extends javax.swing.JFrame {

    Class_Print cp = new Class_Print();
    public static String p_no;
    
    public Print_Reciept_Parts() {
        initComponents();
        cp.PrintGensetReciept();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        print_gensets = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fpe = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        projrct_no = new javax.swing.JLabel();
        customer_name = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        print_genset = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        loc_genset = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        customer_po = new javax.swing.JLabel();
        qoutation_no = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        po_date = new javax.swing.JLabel();
        qoutation_date = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        remarks = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        or_no = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        bank = new javax.swing.JLabel();
        cash_check = new javax.swing.JLabel();
        downpayment = new javax.swing.JLabel();
        paid_on = new javax.swing.JLabel();
        commision = new javax.swing.JLabel();
        agent_name = new javax.swing.JLabel();
        total_cost = new javax.swing.JLabel();
        fpe1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        print_gensets.setBackground(new java.awt.Color(255, 255, 255));
        print_gensets.setPreferredSize(new java.awt.Dimension(850, 1300));
        print_gensets.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Logo/Logo.png"))); // NOI18N
        print_gensets.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 110, 90));

        fpe.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        fpe.setForeground(new java.awt.Color(51, 51, 51));
        fpe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fpe.setText("Parts and Materials");
        fpe.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                fpeAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        print_gensets.add(fpe, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 200, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText(" Address :");
        print_gensets.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 130, 30));

        projrct_no.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        projrct_no.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        print_gensets.add(projrct_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 90, 30));

        customer_name.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        customer_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        print_gensets.add(customer_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 600, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText(" Location of Genset :");
        print_gensets.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 130, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText(" Email / contact no :");
        print_gensets.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 130, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText(" Customer P.O :");
        print_gensets.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 130, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel9.setText(" Cash / Check No:");
        print_gensets.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1090, 130, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel10.setText(" Qoutation Date :");
        print_gensets.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 100, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel11.setText(" P.O Date :");
        print_gensets.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 90, 30));

        print_genset.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(print_genset);

        print_gensets.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 810, 540));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel12.setText(" Quotation No :");
        print_gensets.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 130, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel14.setText("Additional Items :");
        print_gensets.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 960, 130, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel15.setText(" Payment Details :");
        print_gensets.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1010, 130, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel16.setText(" Amount :");
        print_gensets.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1060, 130, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel17.setText(" Date :");
        print_gensets.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1150, 130, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel18.setText(" Bank :");
        print_gensets.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1120, 130, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel20.setText(" Remarks :");
        print_gensets.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1240, 130, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel21.setText(" Balance :");
        print_gensets.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1210, 130, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel22.setText(" OR No :");
        print_gensets.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1180, 130, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel23.setText(" Paid On :");
        print_gensets.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 1080, 130, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel24.setText(" Commision :");
        print_gensets.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 1050, 130, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel25.setText(" Agent Name :");
        print_gensets.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 1020, 130, 30));

        address.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        address.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        print_gensets.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 420, 30));

        loc_genset.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        loc_genset.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        print_gensets.add(loc_genset, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 420, 30));

        contact.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        contact.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        print_gensets.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 420, 30));

        customer_po.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        customer_po.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        print_gensets.add(customer_po, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 420, 30));

        qoutation_no.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        qoutation_no.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        print_gensets.add(qoutation_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 420, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel30.setText(" Customer Name / Company Name :");
        print_gensets.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 210, 30));

        po_date.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        po_date.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        print_gensets.add(po_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 140, 30));

        qoutation_date.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        qoutation_date.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        print_gensets.add(qoutation_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, 140, 30));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel33.setText("Project No :");
        print_gensets.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 90, 30));

        remarks.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        remarks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        remarks.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        print_gensets.add(remarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1240, 260, 30));

        balance.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        balance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balance.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        print_gensets.add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1210, 260, 30));

        or_no.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        or_no.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        or_no.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        print_gensets.add(or_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1180, 260, 30));

        date.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        print_gensets.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1150, 260, 30));

        bank.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        bank.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bank.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        print_gensets.add(bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1120, 260, 30));

        cash_check.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cash_check.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cash_check.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        print_gensets.add(cash_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1090, 260, 30));

        downpayment.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        downpayment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        downpayment.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        print_gensets.add(downpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1060, 260, 30));

        paid_on.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        paid_on.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paid_on.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        print_gensets.add(paid_on, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 1080, 230, 30));

        commision.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        commision.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        commision.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        print_gensets.add(commision, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 1050, 230, 30));

        agent_name.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        agent_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agent_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        print_gensets.add(agent_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 1020, 230, 30));

        total_cost.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        total_cost.setText(" Total contract Price :");
        total_cost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        print_gensets.add(total_cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 960, 340, 30));

        fpe1.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        fpe1.setForeground(new java.awt.Color(51, 51, 51));
        fpe1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fpe1.setText(" Field Power Enterprises");
        fpe1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                fpe1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        print_gensets.add(fpe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 320, 50));

        jScrollPane1.setViewportView(print_gensets);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 630));

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CLOSE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 220, 50));

        jPanel2.setBackground(new java.awt.Color(0, 255, 85));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PRINT");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 220, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 920, 70));

        setBounds(440, 13, 916, 698);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
      PrinterJob printjob = PrinterJob.getPrinterJob();
      printjob.setJobName("Printing the Genset");
      
      
        printjob.setPrintable(new Printable() {
          @Override
          public int print(Graphics pg, PageFormat pf, int pageNum) {
              if(pageNum>0){
                  return Printable.NO_SUCH_PAGE;
              }
              Graphics2D g2 = (Graphics2D)pg;
              g2.translate(pf.getImageableX(), pf.getImageableY());
              g2.scale(0.69,0.62);
              
              print_gensets.print(g2);
              return 0;
              
          }
      });
        
        boolean ok = printjob.printDialog();
        if(ok)
        {
            try {
            printjob.print();
        } catch (PrinterException e){};
        }
        

    
    }//GEN-LAST:event_jLabel4MouseClicked

    private void fpeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_fpeAncestorAdded
       String Banner = fpe1.getText();
       String id = AddCart.project_no.getText();
        if(Banner.equals(" Field Power Enterprises")){
                try{
                PreparedStatement ps=FPE_DB.getConnection().prepareStatement("SELECT `PROJECT NO`,(SELECT `NAME` FROM `customer_table` WHERE `customer_table`.`ID`= `payment_menthod`.`CUSTOMER ID`) AS `CUSTOMER NAME`,(SELECT `ADDRESS` FROM `customer_table` WHERE `customer_table`.`ID`= `payment_menthod`.`CUSTOMER ID`) AS `ADDRESS`,(SELECT `CONTACT` FROM `customer_table` WHERE `customer_table`.`ID`= `payment_menthod`.`CUSTOMER ID`) AS `CONTACT`, `CUSTOMER P O NO`, `P O DATE`, `QUOTATION NO`, `QUOTATION DATE`,`LOCATION`,(SELECT `NAME` FROM `agent_table` WHERE `agent_table`.`ID`= `payment_menthod`.`AGENT ID`) AS `AGENT NAME`,`TOTAL AMOUNT`, `DOWNPAYMENT`, `CASH / CHECK`, `BANK`, `DOWNPAYMENT DATE`, `O R NO`, `DOWNPAYMENT REMARKS`, `BALANCE`, `BALANCE REMARKS` FROM `payment_menthod` WHERE `PROJECT NO`='"+id+"'");
                ResultSet rs = ps.executeQuery();
                while(rs.next()){
                    
                    projrct_no.setText(rs.getString("PROJECT NO"));
                    p_no = rs.getString("PROJECT NO");
                    customer_name.setText(rs.getString("CUSTOMER NAME"));
                    address.setText(rs.getString("ADDRESS"));
                    loc_genset.setText(rs.getString("LOCATION"));
                    contact.setText(rs.getString("CONTACT"));
                    customer_po.setText(rs.getString("CUSTOMER P O NO"));
                    po_date.setText(rs.getString("P O DATE"));
                    qoutation_no.setText(rs.getString("QUOTATION NO"));
                    qoutation_date.setText(rs.getString("QUOTATION DATE"));
                    
                    
                    
                    total_cost.setText(" Total Contract Price :  "+rs.getString("TOTAL AMOUNT"));
                    
                    downpayment.setText(rs.getString("DOWNPAYMENT"));
                    cash_check.setText(rs.getString("CASH / CHECK"));
                    bank.setText(rs.getString("BANK"));
                    date.setText(rs.getString("DOWNPAYMENT DATE"));
                    or_no.setText(rs.getString("O R NO"));
                    balance.setText(rs.getString("BALANCE"));
                    remarks.setText(rs.getString("BALANCE REMARKS"));
                    agent_name.setText(rs.getString("AGENT NAME"));
                    
                    try{
                     ps = FPE_DB.getConnection().prepareStatement("SELECT   `BRAND`, `TYPE`,  `SELLER PRICE` AS `PRICE`, `QUANTITY`, `TOTAL PRICE` FROM `history_table` WHERE `CATEGORY` != 'GENERATOR' AND `PROJECT NO`= "+p_no+"");
                     rs = ps.executeQuery();
                     print_genset.setModel(DbUtils.resultSetToTableModel(rs));
                     print_genset.getColumnModel().getColumn(0).setMaxWidth(100);
                    }catch(Exception e){
              //System.out.println(e);
                    }
                            
                }
            }
            catch(Exception e){
                e.printStackTrace();
            }
       }
    }//GEN-LAST:event_fpeAncestorAdded

    private void fpe1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_fpe1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_fpe1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print_Reciept_Parts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print_Reciept_Parts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print_Reciept_Parts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print_Reciept_Parts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Print_Reciept_Parts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JLabel agent_name;
    private javax.swing.JLabel balance;
    private javax.swing.JLabel bank;
    private javax.swing.JLabel cash_check;
    private javax.swing.JLabel commision;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel customer_name;
    private javax.swing.JLabel customer_po;
    private javax.swing.JLabel date;
    private javax.swing.JLabel downpayment;
    private javax.swing.JLabel fpe;
    private javax.swing.JLabel fpe1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel loc_genset;
    private javax.swing.JLabel or_no;
    private javax.swing.JLabel paid_on;
    private javax.swing.JLabel po_date;
    public static javax.swing.JTable print_genset;
    private javax.swing.JPanel print_gensets;
    private javax.swing.JLabel projrct_no;
    private javax.swing.JLabel qoutation_date;
    private javax.swing.JLabel qoutation_no;
    private javax.swing.JLabel remarks;
    private javax.swing.JLabel total_cost;
    // End of variables declaration//GEN-END:variables

    private void printRecord(JPanel print_gensets) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void print(JPanel print_gensets) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
