/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FPE;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;


/**
 *
 * @author ROBLES
 */
public class Process_Genset extends javax.swing.JFrame {

    public static byte[] images = null;
    

    
    Connection con;
    public Process_Genset() {
        initComponents();
     con = FPE_DB.getConnection();
      Class_Graph cg = new Class_Graph();
    cg.yandong();
    cg.isuzu();
    cg.cummins();
    cg.perkins();
    quotations.setEditable(false);
    process.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Process_Genset_energized = new javax.swing.JTextField();
        Process_Genset_tank_cap = new javax.swing.JTextField();
        Process_Genset_Supplier_Price = new javax.swing.JTextField();
        Process_Genset_Suppiler_name = new javax.swing.JTextField();
        Process_Genset_Oil_Usage = new javax.swing.JTextField();
        Process_Genset_Technician = new javax.swing.JTextField();
        Process_Genset_Updated_At = new javax.swing.JTextField();
        quotation_display_number = new javax.swing.JLabel();
        quotation_display_hypen = new javax.swing.JLabel();
        quotation_display_year = new javax.swing.JLabel();
        Genset_engineNEWOLD = new javax.swing.JLabel();
        Genset_alterNEWOLD = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Process_Genset_Display = new javax.swing.JLabel();
        KG2_ADD_STOCK_GENSET = new keeptoo.KGradientPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        Process_Genset_pic = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        id3 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        quotations = new javax.swing.JTextField();
        Process_Genset_Dealing_Info = new javax.swing.JTextField();
        Process_Genset_Agent_name = new javax.swing.JTextField();
        Process_Genset_Customer_contact = new javax.swing.JTextField();
        Process_Genset_model = new javax.swing.JTextField();
        Process_Genset_id = new javax.swing.JTextField();
        Process_Genset_brand = new javax.swing.JTextField();
        Process_Genset_Alter_Serial = new javax.swing.JTextField();
        Process_Genset_dimension = new javax.swing.JTextField();
        Process_Genset_price = new javax.swing.JTextField();
        Process_Genset_Engine_Serial = new javax.swing.JTextField();
        Process_Genset_kva = new javax.swing.JTextField();
        Process_Genset_phasing = new javax.swing.JTextField();
        Process_Genset_type = new javax.swing.JTextField();
        Process_Genset_Agent_contact = new javax.swing.JTextField();
        Process_Genset_Customer_email = new javax.swing.JTextField();
        Process_Genset_Customer_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Process_Genset_Customer_address = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        Supplier_List_Btn = new javax.swing.JLabel();
        Stock_Genset_Panel_Update = new javax.swing.JPanel();
        Stock_Genset_Update = new javax.swing.JLabel();
        Stock_Genset_Panel_Back = new javax.swing.JPanel();
        Stock_Genset_Back = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Process_Genset_StartingSystem = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        Process_Genset_Frame = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        Process_Genset_Weight = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        yr = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        process = new javax.swing.JLabel();

        Process_Genset_energized.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_energized.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_energized.setBorder(null);

        Process_Genset_tank_cap.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_tank_cap.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_tank_cap.setBorder(null);

        Process_Genset_Supplier_Price.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_Supplier_Price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_Supplier_Price.setBorder(null);

        Process_Genset_Suppiler_name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_Suppiler_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_Suppiler_name.setBorder(null);

        Process_Genset_Oil_Usage.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_Oil_Usage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_Oil_Usage.setBorder(null);

        Process_Genset_Technician.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_Technician.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_Technician.setBorder(null);

        Process_Genset_Updated_At.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_Updated_At.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_Updated_At.setBorder(null);

        quotation_display_number.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        quotation_display_number.setAlignmentY(1.0F);

        quotation_display_hypen.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        quotation_display_hypen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quotation_display_hypen.setText("-");
        quotation_display_hypen.setAlignmentY(1.0F);

        quotation_display_year.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        quotation_display_year.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        quotation_display_year.setAlignmentY(1.0F);

        Genset_engineNEWOLD.setText("jLabel1");

        Genset_alterNEWOLD.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(2, 71, 94));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Process_Genset_Display.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Process_Genset_Display.setForeground(new java.awt.Color(255, 255, 255));
        Process_Genset_Display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Process_Genset_Display.setText("GENSET PROCESSING");
        Process_Genset_Display.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Process_Genset_DisplayAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel4.add(Process_Genset_Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 470, 80));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 100));

        KG2_ADD_STOCK_GENSET.setkEndColor(new java.awt.Color(42, 142, 142));
        KG2_ADD_STOCK_GENSET.setkGradientFocus(700);
        KG2_ADD_STOCK_GENSET.setkStartColor(new java.awt.Color(42, 142, 142));
        KG2_ADD_STOCK_GENSET.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(20, 31, 31));
        jLabel20.setText("UNIT TYPE");
        jLabel20.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 120, 30));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(20, 31, 31));
        jLabel22.setText("DIMENSION");
        jLabel22.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 120, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(20, 31, 31));
        jLabel2.setText("BRAND");
        jLabel2.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 80, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(20, 31, 31));
        jLabel7.setText("KVA");
        jLabel7.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 70, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(20, 31, 31));
        jLabel11.setText("ENGINE_SN");
        jLabel11.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 120, 30));

        a.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        a.setForeground(new java.awt.Color(20, 31, 31));
        a.setText("ID");
        a.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 80, 30));

        Process_Genset_pic.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        Process_Genset_pic.setForeground(new java.awt.Color(20, 31, 31));
        Process_Genset_pic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Process_Genset_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Drawer_Btn/Default_Imge.png"))); // NOI18N
        Process_Genset_pic.setAlignmentY(1.0F);
        Process_Genset_pic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 31, 31)));
        Process_Genset_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Process_Genset_picMouseClicked(evt);
            }
        });
        KG2_ADD_STOCK_GENSET.add(Process_Genset_pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 270, 170));

        jLabel29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(20, 31, 31));
        jLabel29.setText("PRICE");
        jLabel29.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 120, 30));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(20, 31, 31));
        jLabel15.setText("ALTERNATOR_SN");
        jLabel15.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 130, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(20, 31, 31));
        jLabel5.setText("MODEL");
        jLabel5.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 80, 30));

        id1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        id1.setText("NAME");
        id1.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 100, 28));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setText("ADDRESS");
        jLabel21.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 100, 28));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("EMAIL ");
        jLabel19.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, 100, 28));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("CONTACT NO.");
        jLabel18.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 100, 28));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(20, 31, 31));
        jLabel10.setText("PHASING");
        jLabel10.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 70, 30));

        id3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        id3.setText("AGENT NAME");
        id3.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(id3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, 100, 30));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setText("CONTACT");
        jLabel24.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 100, 30));

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setText("DEALING INFO");
        jLabel25.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 100, 28));

        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setText("QUOTATION");
        jLabel26.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 100, 30));

        quotations.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        quotations.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quotations.setBorder(null);
        KG2_ADD_STOCK_GENSET.add(quotations, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 420, 180, 30));

        Process_Genset_Dealing_Info.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_Dealing_Info.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_Dealing_Info.setBorder(null);
        KG2_ADD_STOCK_GENSET.add(Process_Genset_Dealing_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, 180, 28));

        Process_Genset_Agent_name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_Agent_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_Agent_name.setBorder(null);
        KG2_ADD_STOCK_GENSET.add(Process_Genset_Agent_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 340, 180, 30));

        Process_Genset_Customer_contact.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_Customer_contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_Customer_contact.setBorder(null);
        KG2_ADD_STOCK_GENSET.add(Process_Genset_Customer_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, 180, 28));

        Process_Genset_model.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_model.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_model.setBorder(null);
        KG2_ADD_STOCK_GENSET.add(Process_Genset_model, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 190, 30));

        Process_Genset_id.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_id.setBorder(null);
        KG2_ADD_STOCK_GENSET.add(Process_Genset_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 190, 30));

        Process_Genset_brand.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_brand.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_brand.setBorder(null);
        KG2_ADD_STOCK_GENSET.add(Process_Genset_brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 190, 30));

        Process_Genset_Alter_Serial.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_Alter_Serial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_Alter_Serial.setBorder(null);
        KG2_ADD_STOCK_GENSET.add(Process_Genset_Alter_Serial, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 190, 30));

        Process_Genset_dimension.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_dimension.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_dimension.setBorder(null);
        KG2_ADD_STOCK_GENSET.add(Process_Genset_dimension, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 190, 30));

        Process_Genset_price.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_price.setBorder(null);
        KG2_ADD_STOCK_GENSET.add(Process_Genset_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 190, 30));

        Process_Genset_Engine_Serial.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_Engine_Serial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_Engine_Serial.setBorder(null);
        KG2_ADD_STOCK_GENSET.add(Process_Genset_Engine_Serial, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 190, 30));

        Process_Genset_kva.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_kva.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_kva.setBorder(null);
        KG2_ADD_STOCK_GENSET.add(Process_Genset_kva, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 190, 30));

        Process_Genset_phasing.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_phasing.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_phasing.setBorder(null);
        KG2_ADD_STOCK_GENSET.add(Process_Genset_phasing, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 190, 30));

        Process_Genset_type.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_type.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_type.setBorder(null);
        KG2_ADD_STOCK_GENSET.add(Process_Genset_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 190, 30));

        Process_Genset_Agent_contact.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_Agent_contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_Agent_contact.setBorder(null);
        KG2_ADD_STOCK_GENSET.add(Process_Genset_Agent_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, 180, 30));

        Process_Genset_Customer_email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_Customer_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_Customer_email.setBorder(null);
        KG2_ADD_STOCK_GENSET.add(Process_Genset_Customer_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, 180, 28));

        Process_Genset_Customer_name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_Customer_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_Customer_name.setBorder(null);
        KG2_ADD_STOCK_GENSET.add(Process_Genset_Customer_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, 180, 28));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Process_Genset_Customer_address.setColumns(10);
        Process_Genset_Customer_address.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_Customer_address.setRows(5);
        Process_Genset_Customer_address.setTabSize(5);
        Process_Genset_Customer_address.setAlignmentX(3.0F);
        Process_Genset_Customer_address.setAlignmentY(2.0F);
        Process_Genset_Customer_address.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        Process_Genset_Customer_address.setMargin(new java.awt.Insets(8, 8, 8, 8));
        jScrollPane1.setViewportView(Process_Genset_Customer_address);

        KG2_ADD_STOCK_GENSET.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, 180, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 179));

        Supplier_List_Btn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Supplier_List_Btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Supplier_List_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Btn/Btn_Customer.png"))); // NOI18N
        Supplier_List_Btn.setText(" CUSTOMER LIST   ");
        Supplier_List_Btn.setAlignmentY(1.0F);
        Supplier_List_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Supplier_List_BtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Supplier_List_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Supplier_List_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        KG2_ADD_STOCK_GENSET.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 250, 180, 30));

        Stock_Genset_Panel_Update.setBackground(new java.awt.Color(51, 187, 255));
        Stock_Genset_Panel_Update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 246, 26)));

        Stock_Genset_Update.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        Stock_Genset_Update.setForeground(new java.awt.Color(255, 255, 255));
        Stock_Genset_Update.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Stock_Genset_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Btn/Btn_Process.png"))); // NOI18N
        Stock_Genset_Update.setText(" PROCEED");
        Stock_Genset_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Stock_Genset_UpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Stock_Genset_UpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Stock_Genset_UpdateMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Stock_Genset_Panel_UpdateLayout = new javax.swing.GroupLayout(Stock_Genset_Panel_Update);
        Stock_Genset_Panel_Update.setLayout(Stock_Genset_Panel_UpdateLayout);
        Stock_Genset_Panel_UpdateLayout.setHorizontalGroup(
            Stock_Genset_Panel_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Stock_Genset_Update, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
        );
        Stock_Genset_Panel_UpdateLayout.setVerticalGroup(
            Stock_Genset_Panel_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Stock_Genset_Update, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        KG2_ADD_STOCK_GENSET.add(Stock_Genset_Panel_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 210, 50));

        Stock_Genset_Panel_Back.setBackground(new java.awt.Color(255, 173, 51));
        Stock_Genset_Panel_Back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 246, 26)));

        Stock_Genset_Back.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        Stock_Genset_Back.setForeground(new java.awt.Color(255, 255, 255));
        Stock_Genset_Back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Stock_Genset_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Btn/Btn_Backss.png"))); // NOI18N
        Stock_Genset_Back.setText(" BACK");
        Stock_Genset_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Stock_Genset_BackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Stock_Genset_BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Stock_Genset_BackMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Stock_Genset_Panel_BackLayout = new javax.swing.GroupLayout(Stock_Genset_Panel_Back);
        Stock_Genset_Panel_Back.setLayout(Stock_Genset_Panel_BackLayout);
        Stock_Genset_Panel_BackLayout.setHorizontalGroup(
            Stock_Genset_Panel_BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Stock_Genset_Back, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
        );
        Stock_Genset_Panel_BackLayout.setVerticalGroup(
            Stock_Genset_Panel_BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Stock_Genset_Back, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        KG2_ADD_STOCK_GENSET.add(Stock_Genset_Panel_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, 210, 50));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(20, 31, 31));
        jLabel16.setText("STARTING SYSTEM");
        jLabel16.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 130, 30));

        Process_Genset_StartingSystem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_StartingSystem.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_StartingSystem.setBorder(null);
        KG2_ADD_STOCK_GENSET.add(Process_Genset_StartingSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 190, 30));

        jLabel27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(20, 31, 31));
        jLabel27.setText("FRAME");
        jLabel27.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 130, 30));

        Process_Genset_Frame.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_Frame.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_Frame.setBorder(null);
        KG2_ADD_STOCK_GENSET.add(Process_Genset_Frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 190, 30));

        jLabel28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(20, 31, 31));
        jLabel28.setText("WEIGHT");
        jLabel28.setAlignmentY(1.0F);
        KG2_ADD_STOCK_GENSET.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 130, 30));

        Process_Genset_Weight.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Process_Genset_Weight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Process_Genset_Weight.setBorder(null);
        KG2_ADD_STOCK_GENSET.add(Process_Genset_Weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 190, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 0));
        jLabel12.setToolTipText("");
        jLabel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 31, 31)), "GENSET INFORMATION", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 20), new java.awt.Color(20, 31, 31))); // NOI18N
        KG2_ADD_STOCK_GENSET.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 670, 490));

        yr.setText("YEAR - QUOTATION");
        yr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yrActionPerformed(evt);
            }
        });
        KG2_ADD_STOCK_GENSET.add(yr, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 460, 180, 30));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setToolTipText("");
        jLabel17.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 31, 31)), "AGENT INFORMATION", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 20), new java.awt.Color(20, 31, 31))); // NOI18N
        KG2_ADD_STOCK_GENSET.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 330, 210));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setToolTipText("");
        jLabel23.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 31, 31)), "CUSTOMER INFORMATION", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 20), new java.awt.Color(20, 31, 31))); // NOI18N
        KG2_ADD_STOCK_GENSET.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 330, 270));

        process.setText("1");
        KG2_ADD_STOCK_GENSET.add(process, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 40, -1));

        getContentPane().add(KG2_ADD_STOCK_GENSET, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1070, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Process_Genset_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Process_Genset_picMouseClicked

    }//GEN-LAST:event_Process_Genset_picMouseClicked

    private void Stock_Genset_UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stock_Genset_UpdateMouseClicked
    Class_tables ct = new Class_tables();
    
    Date today = new Date();
    SimpleDateFormat date = new SimpleDateFormat("MM/dd/yyyy");
    String getdate = date.format(today);
    
    String Banner           = Process_Genset_Display.getText();
    String id               = Process_Genset_id.getText().toUpperCase();
    String brand            = Process_Genset_brand.getText().toUpperCase(); 
    String model            = Process_Genset_model.getText().toUpperCase();
    String kva              = Process_Genset_kva.getText().toUpperCase();
    String phasing          = Process_Genset_phasing.getText().toUpperCase(); 
    String type             = Process_Genset_type.getText().toUpperCase(); 
    String dimen            = Process_Genset_dimension.getText().toUpperCase();
    String seller_price     = Process_Genset_price.getText().toUpperCase(); 
    String engine_sn        = Genset_engineNEWOLD.getText().toUpperCase() +" - "+ Process_Genset_Engine_Serial.getText().toUpperCase();
    String alters1_sn       = Genset_alterNEWOLD.getText().toUpperCase() +" - "+ Process_Genset_Alter_Serial.getText().toUpperCase();
    
    
    
     
    String  c_name          = Process_Genset_Customer_name.getText().toUpperCase();
    String  c_add           = Process_Genset_Customer_address.getText().toUpperCase();
    String  c_email         = Process_Genset_Customer_email.getText().toUpperCase();
    String  c_contact       = Process_Genset_Customer_contact.getText().toUpperCase();
    
    String c_deal           = Process_Genset_Dealing_Info.getText();
    String agent_name       = Process_Genset_Agent_name.getText();
    String agent_contact    = Process_Genset_Agent_contact.getText();
    String quotation        = quotations.getText();

    String sup_price       = Process_Genset_Supplier_Price.getText();
    String date_recieved  = getdate ;
    String sup_name       = Process_Genset_Suppiler_name.getText();
    String energized_date = Process_Genset_energized.getText();
    String tank_cap       = Process_Genset_tank_cap.getText();
    String oil_usage      = Process_Genset_Oil_Usage.getText();
    String tech           = Process_Genset_Technician.getText();
    String esystem = Process_Genset_StartingSystem.getText();
    String weight = Process_Genset_Weight.getText();
    String frame = Process_Genset_Frame.getText();
    String updated_at = Process_Genset_Updated_At.getText();

    
    String processed = process.getText();
    
//    Reciept.Recieipt_c_name.setText(c_name);
//    Reciept.Recieipt_c_address.setText(c_add);
//    Reciept.Receipt_Cooments.setText("");
    String[] getValidQuot = quotation_display_year.getText().split(" - ");
    

    if(brand.equals("") || model.equals("") || kva.equals("") || phasing.equals("") || type.equals("") || dimen.equals("") || seller_price.equals("") || engine_sn.equals("") || alters1_sn.equals("") || c_name.equals("") || c_add.equals("") || c_email.equals("") || c_contact.equals("") || c_deal.equals("") || agent_name.equals("") || agent_contact.equals("") || quotation.equals("") || date_recieved.equals("") || sup_name.equals("") || energized_date.equals("") || tank_cap.equals("") || oil_usage.equals("") || tech.equals("") || esystem.equals("") || weight.equals("") || frame.equals("") || updated_at.equals("") ){
        JOptionPane.showMessageDialog(null, "EMPTY SOME FIELDS!","",JOptionPane.INFORMATION_MESSAGE);
        ct.Bin_Genset();ct.Genset();ct.History_Genset();ct.ShopGenset();
    }
    else{
        if(getValidQuot[0].equals("0000")){
            JOptionPane.showMessageDialog(null, "Please Check Quotation");
         
        }
        else if (id.equals("") || brand.equals("") || model.equals("") || kva.equals("") || phasing.equals("") || type.equals("") || dimen.equals("") || seller_price.equals("") || engine_sn.equals("") || alters1_sn.equals("") || c_name.equals("") || c_add.equals("") || c_email.equals("") || c_contact.equals("") || c_deal.equals("") || agent_name.equals("") || agent_contact.equals("") || quotation.equals("") || sup_price.equals("") || date_recieved.equals("") || sup_name.equals("") || energized_date.equals("") || tank_cap.equals("") || oil_usage.equals("") || tech.equals("") || updated_at.equals("")){
         JOptionPane.showMessageDialog(null, "EMPTY SOME FIELDS!!","",JOptionPane.INFORMATION_MESSAGE);
         ct.Bin_Genset();ct.Genset();ct.History_Genset();ct.ShopGenset();
        }else{
    //        int opt = JOptionPane.showConfirmDialog(null, "YOU WANT TO PRINT THIS PRODUCT ? ","",JOptionPane.YES_NO_OPTION);
    //        if(opt==0){
    //            if(JOptionPane.YES_NO_OPTION == JOptionPane.YES_OPTION)
    //            {
               
              
                    if(processed.equals("1")){
                        //insert histoty_genset_table
                        //insert bin_genset
                        // delete insert_genset
                        ct.Bin_Genset();ct.Genset();ct.History_Genset();ct.ShopGenset();
                        if(!Class_Bin.Historygenset(id,brand, model, kva, phasing, type, dimen, sup_price,  seller_price, engine_sn, alters1_sn, date_recieved , images, sup_name, energized_date, tank_cap, oil_usage, tech, esystem, weight, frame , updated_at, quotation, c_name, c_add, c_email, c_contact, c_deal, agent_name, agent_contact) && !Class_Bin.gensetTable(id) )
                         {
                              JOptionPane.showMessageDialog(null, "SUCCESS");

                             try{

                                     JasperDesign jasperdesign =JRXmlLoader.load("C:/Users/"+Mainpage.located+"/Documents/NetBeansProjects/FieldPowerEnterprises/src/FPE/printgenset.jrxml");
                                     String sql = "SELECT `ID`, `BRAND`, `MODEL`, `KVA`, `PHASING`, `UNIT_TYPE`, `DIMENSION`,`PRICE`, FORMAT(`SELLER PRICE`,'#,##0.00') AS `SELLER PRICE`, `ENGINE_SERIAL_NO`, `ALTERNATOR_SERIAL_NO`, `DATE`, `IMAGE`, `SUPPLIER`, `ENERGIZED DATE`, `TANK CAPACITY`, `OIL USAGE`, `TECHNICIAN`, `UPDATED AT`, `QUOTATION`, `CUSTOMER_NAME`, `CUSTOMER_ADDRESS`, `CUSTOMER_EMAIL`, `CUSTOMER_CONTACT`, `DEALING INFO`, `AGENT_NAME`, `AGENT_CONTACT`, `ID_GENSET` FROM `history_genset_table` ORDER BY `ID` DESC LIMIT 1";
                                     JRDesignQuery jrdesignquery = new JRDesignQuery();
                                     jrdesignquery.setText(sql);
                                     jasperdesign.setQuery(jrdesignquery);
                                     JasperReport jaspereport = JasperCompileManager.compileReport(jasperdesign);

                                 HashMap<String, Object> params = new HashMap<String, Object>();
                                 String subject = "Quotation for Brand "+kva+" "+" "+ brand +" "+model;
                                 String title = kva+ " "+brand+" "+ model;
                                 BufferedImage image = ImageIO.read(getClass().getResource("logo.png"));
                                 params.put("logo", image );
                                 params.put("subject",subject);
                                 params.put("title",title);
                                 params.put("start_system",esystem);
                                 params.put("weight",weight);
                                 params.put("frame",frame);
                                 JasperPrint jasperprint = JasperFillManager.fillReport(jaspereport, params,con);
                                 JasperViewer.viewReport(jasperprint, false);


                                 }
                                 catch(Exception e){
                                     System.out.println(e.getMessage());
                                 }        
                             ct.Bin_Genset();ct.Genset();ct.History_Genset();ct.ShopGenset();
                         }                    
                        //JOptionPane.showMessageDialog(null, "1");
                        process.setText("2");//update
                        ct.Bin_Genset();ct.Genset();ct.History_Genset();ct.ShopGenset();
                    }else{
                        ct.Bin_Genset();ct.Genset();ct.History_Genset();ct.ShopGenset();
                        if(processed.equals("2")){
                        ct.Bin_Genset();ct.Genset();ct.History_Genset();ct.ShopGenset();
                           // JOptionPane.showMessageDialog(null, "2");
                           // update class
                        if(!Class_Bin.HistorygensetUpdate(id,brand, model, kva, phasing, type, dimen, sup_price,  seller_price, engine_sn, alters1_sn, date_recieved , images, sup_name, energized_date, tank_cap, oil_usage, tech, esystem, weight, frame , updated_at, quotation, c_name, c_add, c_email, c_contact, c_deal, agent_name, agent_contact) && !Class_Bin.gensetTable(id) )
                         {
                             ct.Bin_Genset();ct.Genset();ct.History_Genset();ct.ShopGenset();
                              JOptionPane.showMessageDialog(null, "SUCCESS");
                             try{

                                     JasperDesign jasperdesign =JRXmlLoader.load("C:/Users/"+Mainpage.located+"/Documents/NetBeansProjects/FieldPowerEnterprises/src/FPE/printgenset.jrxml");
                                     String sql = "SELECT ID,`BRAND`, `MODEL`, `KVA`, `PHASING`, `UNIT_TYPE`, `DIMENSION`,`PRICE`, FORMAT(`SELLER PRICE`,'#,##0.00') AS `SELLER PRICE`, `ENGINE_SERIAL_NO`, `ALTERNATOR_SERIAL_NO`, `DATE`, `IMAGE`, `SUPPLIER`, `ENERGIZED DATE`, `TANK CAPACITY`, `OIL USAGE`, `TECHNICIAN`, `UPDATED AT`, `QUOTATION`, `CUSTOMER_NAME`, `CUSTOMER_ADDRESS`, `CUSTOMER_EMAIL`, `CUSTOMER_CONTACT`, `DEALING INFO`, `AGENT_NAME`, `AGENT_CONTACT`, `ID_GENSET` FROM `history_genset_table` ORDER BY `ID` DESC LIMIT 1";
                                     JRDesignQuery jrdesignquery = new JRDesignQuery();
                                     jrdesignquery.setText(sql);
                                     jasperdesign.setQuery(jrdesignquery);
                                     JasperReport jaspereport = JasperCompileManager.compileReport(jasperdesign);

                                 HashMap<String, Object> params = new HashMap<String, Object>();
                                 String subject = "Quotation for Brand "+kva+" "+" "+ brand +" "+model;
                                 String title = kva+ " "+brand+" "+ model;
                                 BufferedImage image = ImageIO.read(getClass().getResource("logo.png"));
                                 params.put("logo", image );
                                 params.put("subject",subject);
                                 params.put("title",title);
                                 params.put("start_system",esystem);
                                 params.put("weight",weight);
                                 params.put("frame",frame);
                                 JasperPrint jasperprint = JasperFillManager.fillReport(jaspereport, params,con);
                                 JasperViewer.viewReport(jasperprint, false);


                                 }
                                 catch(Exception e){
                                     System.out.println(e.getMessage());
                                    JOptionPane.showMessageDialog(null, e);
                                 }
                             ct.Bin_Genset();ct.Genset();ct.History_Genset();ct.ShopGenset();
                         }                
                        }
                    }


               // }
            //}

        }        
    }
    

 ct.Bin_Genset();ct.Genset();ct.History_Genset();ct.ShopGenset();

    }//GEN-LAST:event_Stock_Genset_UpdateMouseClicked

    private void Stock_Genset_UpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stock_Genset_UpdateMouseEntered
      
        Stock_Genset_Panel_Update.setBackground(new Color(51, 207, 255));
    }//GEN-LAST:event_Stock_Genset_UpdateMouseEntered

    private void Stock_Genset_UpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stock_Genset_UpdateMouseExited
     
        Stock_Genset_Panel_Update.setBackground(new Color(51, 187, 255));
    }//GEN-LAST:event_Stock_Genset_UpdateMouseExited

    private void Stock_Genset_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stock_Genset_BackMouseClicked
//        JTab.setSelectedIndex(1);
    dispose();
    }//GEN-LAST:event_Stock_Genset_BackMouseClicked

    private void Stock_Genset_BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stock_Genset_BackMouseEntered
      
        Stock_Genset_Panel_Back.setBackground(new Color(255,214,122));
    }//GEN-LAST:event_Stock_Genset_BackMouseEntered

    private void Stock_Genset_BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stock_Genset_BackMouseExited
        Stock_Genset_Panel_Back.setBackground(new Color(255,194,102));
    }//GEN-LAST:event_Stock_Genset_BackMouseExited

    private void Process_Genset_DisplayAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Process_Genset_DisplayAncestorAdded
        String Banner = Process_Genset_Display.getText();
         Date today = new Date();
        if(Banner.equals("GENSET PROCESSING")){
            //quotations.setEditable(false);
            try{
            String id = Process_Genset_id.getText();
            PreparedStatement ps=FPE_DB.getConnection().prepareStatement("SELECT `IMAGE` FROM `genset_table` WHERE `ID` = '"+id+"'");
            ResultSet rs = ps.executeQuery();
                while(rs.next()){
  
                images = rs.getBytes("IMAGE");
                ImageIcon imageicon = new ImageIcon (new ImageIcon(images).getImage().getScaledInstance(Process_Genset_pic.getWidth(), Process_Genset_pic.getHeight(),Image.SCALE_SMOOTH) );
                Process_Genset_pic.setIcon(imageicon); 
                }
            }
            catch(Exception e){
                e.printStackTrace();
            }
            
            try{
            PreparedStatement ps=FPE_DB.getConnection().prepareStatement("SELECT `QUOTATION` FROM `history_genset_table` ORDER BY `ID` DESC LIMIT 1");
            ResultSet rs = ps.executeQuery();
            //quotations.setText("0000 - 1");
            quotation_display_year.setText("0000");
            quotation_display_number.setText("1"); 
                while(rs.next()){
                    SimpleDateFormat quot_date = new SimpleDateFormat("yyyy");             
                    
                    if(rs.getString("QUOTATION").equals("")){
//                        quotations.setEditable(false);
                          quotation_display_year.setText("0000");
                          quotation_display_number.setText("1"); 
//                           if(quotations.getText().equals("0000" + " - 1")){
//                           quotation_display_year.setText("0000");
//                           quotation_display_number.setText("1");      
//                           }
                           try{
                               quotations.setText(year.yr.getSelectedItem().toString()+" - "+year.quot_number.getText());
                               quotation_display_year.setText(year.yr.getSelectedItem().toString());
                               quotation_display_number.setText(year.quot_number.getText());  

                           }catch(Exception e ){
                              // e.printStackTrace();
                           }
                    }
                    else{
//                        String[] quot = rs.getString("QUOTATION").split(" - ");
//                        int getRead = Integer.parseInt(quot[1].toString());
//                        int output = getRead + 1;
//                        if(quot[1].equals( rs.getString("QUOTATION").split(" - ")[1] ) && quot[0].equals( rs.getString("QUOTATION").split(" - ")[0] )){
//                            
//                            quotation_display_year.setText(""+quot[0]);
//                            quotation_display_number.setText(""+output);
//                            quotations.setText(quot[0]+" - "+output);
//                        }
                            try{
                                quotation_display_year.setText(""+year.yr_select.getText());
                                quotation_display_number.setText(""+year.quot_number.getText());
                                quotations.setText(year.yr_select.getText()+" - "+year.quot_number.getText());
                            } 
                            catch(Exception e){
                                 //e.printStackTrace();
                            }
                    }
                }
            }
            catch(Exception e){
                e.printStackTrace();
            }            
            
        }
    }//GEN-LAST:event_Process_Genset_DisplayAncestorAdded

    private void Supplier_List_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Supplier_List_BtnMouseClicked
        Table_Customer ts = new Table_Customer();
        ts.setVisible(true);
        Table_Customer.Add.setText("SELECT");
        Table_Customer.Path.setText("2");
       
    }//GEN-LAST:event_Supplier_List_BtnMouseClicked

    private void yrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yrActionPerformed
        year yr = new year();
        yr.yearCompared.setText("1");
        yr.setVisible(true);
    }//GEN-LAST:event_yrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Process_Genset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Process_Genset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Process_Genset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Process_Genset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Process_Genset().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Genset_alterNEWOLD;
    public static javax.swing.JLabel Genset_engineNEWOLD;
    public static keeptoo.KGradientPanel KG2_ADD_STOCK_GENSET;
    public static javax.swing.JTextField Process_Genset_Agent_contact;
    public static javax.swing.JTextField Process_Genset_Agent_name;
    public static javax.swing.JTextField Process_Genset_Alter_Serial;
    public static javax.swing.JTextArea Process_Genset_Customer_address;
    public static javax.swing.JTextField Process_Genset_Customer_contact;
    public static javax.swing.JTextField Process_Genset_Customer_email;
    public static javax.swing.JTextField Process_Genset_Customer_name;
    public static javax.swing.JTextField Process_Genset_Dealing_Info;
    public static javax.swing.JLabel Process_Genset_Display;
    public static javax.swing.JTextField Process_Genset_Engine_Serial;
    public static javax.swing.JTextField Process_Genset_Frame;
    public static javax.swing.JTextField Process_Genset_Oil_Usage;
    public static javax.swing.JTextField Process_Genset_StartingSystem;
    public static javax.swing.JTextField Process_Genset_Suppiler_name;
    public static javax.swing.JTextField Process_Genset_Supplier_Price;
    public static javax.swing.JTextField Process_Genset_Technician;
    public static javax.swing.JTextField Process_Genset_Updated_At;
    public static javax.swing.JTextField Process_Genset_Weight;
    public static javax.swing.JTextField Process_Genset_brand;
    public static javax.swing.JTextField Process_Genset_dimension;
    public static javax.swing.JTextField Process_Genset_energized;
    public static javax.swing.JTextField Process_Genset_id;
    public static javax.swing.JTextField Process_Genset_kva;
    public static javax.swing.JTextField Process_Genset_model;
    public static javax.swing.JTextField Process_Genset_phasing;
    public static javax.swing.JLabel Process_Genset_pic;
    public static javax.swing.JTextField Process_Genset_price;
    public static javax.swing.JTextField Process_Genset_tank_cap;
    public static javax.swing.JTextField Process_Genset_type;
    private javax.swing.JLabel Stock_Genset_Back;
    public static javax.swing.JPanel Stock_Genset_Panel_Back;
    public static javax.swing.JPanel Stock_Genset_Panel_Update;
    private javax.swing.JLabel Stock_Genset_Update;
    private javax.swing.JLabel Supplier_List_Btn;
    private javax.swing.JLabel a;
    private javax.swing.JLabel id1;
    private javax.swing.JLabel id3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel process;
    public static javax.swing.JLabel quotation_display_hypen;
    public static javax.swing.JLabel quotation_display_number;
    public static javax.swing.JLabel quotation_display_year;
    public static javax.swing.JTextField quotations;
    private javax.swing.JButton yr;
    // End of variables declaration//GEN-END:variables
}
