/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FPE;



//import static FPE2.Table_Customer.Customer_table;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ROBLES
 */
public class Table_Supplier extends javax.swing.JFrame {
//
    String id = null;
    String name = null;
    String add = null;
    String contact = null;
    
    Class_tables ct = new Class_tables();
    
    public Table_Supplier() {
    initComponents();
        
    ct.Supplier();
      
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        displays = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Supplier_table = new javax.swing.JTable();
        add_panel_supplier = new javax.swing.JPanel();
        Add = new javax.swing.JLabel();
        update_panel_supplier = new javax.swing.JPanel();
        sup_listUpdate = new javax.swing.JLabel();
        delete_panel_supplier = new javax.swing.JPanel();
        sup_del = new javax.swing.JLabel();
        back_panel_supplier = new javax.swing.JPanel();
        Back = new javax.swing.JLabel();
        Supplier_Search = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        back_panel_supplier1 = new javax.swing.JPanel();
        Back1 = new javax.swing.JLabel();
        supplier_id = new javax.swing.JLabel();
        Supplier_path = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(2, 71, 94));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displays.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        displays.setForeground(new java.awt.Color(255, 255, 255));
        displays.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displays.setText("SUPPLIER LIST");
        displays.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                displaysAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel4.add(displays, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 370, 100));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 130));

        kGradientPanel1.setkEndColor(new java.awt.Color(42, 142, 142));
        kGradientPanel1.setkStartColor(new java.awt.Color(42, 142, 142));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Supplier_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Supplier_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Supplier_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Supplier_table);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 78, 880, 350));

        add_panel_supplier.setBackground(new java.awt.Color(35, 215, 176));

        Add.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Btn/Add_Supplier_Btn.PNG"))); // NOI18N
        Add.setText(" ADD");
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddMouseExited(evt);
            }
        });

        javax.swing.GroupLayout add_panel_supplierLayout = new javax.swing.GroupLayout(add_panel_supplier);
        add_panel_supplier.setLayout(add_panel_supplierLayout);
        add_panel_supplierLayout.setHorizontalGroup(
            add_panel_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        add_panel_supplierLayout.setVerticalGroup(
            add_panel_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        kGradientPanel1.add(add_panel_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 150, 50));

        update_panel_supplier.setBackground(new java.awt.Color(66, 139, 202));

        sup_listUpdate.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        sup_listUpdate.setForeground(new java.awt.Color(255, 255, 255));
        sup_listUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sup_listUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Btn/Edit_Supplier_Btn.png"))); // NOI18N
        sup_listUpdate.setText(" UPDATE ");
        sup_listUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sup_listUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sup_listUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sup_listUpdateMouseExited(evt);
            }
        });

        javax.swing.GroupLayout update_panel_supplierLayout = new javax.swing.GroupLayout(update_panel_supplier);
        update_panel_supplier.setLayout(update_panel_supplierLayout);
        update_panel_supplierLayout.setHorizontalGroup(
            update_panel_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(update_panel_supplierLayout.createSequentialGroup()
                .addComponent(sup_listUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        update_panel_supplierLayout.setVerticalGroup(
            update_panel_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sup_listUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        kGradientPanel1.add(update_panel_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 150, 50));

        delete_panel_supplier.setBackground(new java.awt.Color(255, 77, 77));

        sup_del.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        sup_del.setForeground(new java.awt.Color(255, 255, 255));
        sup_del.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sup_del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Btn/Remove_Supplier_Btn.png"))); // NOI18N
        sup_del.setText(" DELETE");
        sup_del.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sup_delMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sup_delMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sup_delMouseExited(evt);
            }
        });

        javax.swing.GroupLayout delete_panel_supplierLayout = new javax.swing.GroupLayout(delete_panel_supplier);
        delete_panel_supplier.setLayout(delete_panel_supplierLayout);
        delete_panel_supplierLayout.setHorizontalGroup(
            delete_panel_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delete_panel_supplierLayout.createSequentialGroup()
                .addComponent(sup_del, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );
        delete_panel_supplierLayout.setVerticalGroup(
            delete_panel_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sup_del, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        kGradientPanel1.add(delete_panel_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, 150, 50));

        back_panel_supplier.setBackground(new java.awt.Color(185, 144, 149));

        Back.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Btn/arrow_35px.png"))); // NOI18N
        Back.setText(" BACK  ");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackMouseExited(evt);
            }
        });

        javax.swing.GroupLayout back_panel_supplierLayout = new javax.swing.GroupLayout(back_panel_supplier);
        back_panel_supplier.setLayout(back_panel_supplierLayout);
        back_panel_supplierLayout.setHorizontalGroup(
            back_panel_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back_panel_supplierLayout.createSequentialGroup()
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );
        back_panel_supplierLayout.setVerticalGroup(
            back_panel_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        kGradientPanel1.add(back_panel_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 470, 150, 50));

        Supplier_Search.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Supplier_Search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Supplier_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Supplier_SearchKeyPressed(evt);
            }
        });
        kGradientPanel1.add(Supplier_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 220, 31));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Btn/Btn_Search.png"))); // NOI18N
        kGradientPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 35, 31));

        back_panel_supplier1.setBackground(new java.awt.Color(255, 102, 255));

        Back1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        Back1.setForeground(new java.awt.Color(255, 255, 255));
        Back1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Btn/Select_Btn.png"))); // NOI18N
        Back1.setText(" SELECT  ");
        Back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Back1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Back1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Back1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout back_panel_supplier1Layout = new javax.swing.GroupLayout(back_panel_supplier1);
        back_panel_supplier1.setLayout(back_panel_supplier1Layout);
        back_panel_supplier1Layout.setHorizontalGroup(
            back_panel_supplier1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Back1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        back_panel_supplier1Layout.setVerticalGroup(
            back_panel_supplier1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Back1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        kGradientPanel1.add(back_panel_supplier1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 150, 50));
        kGradientPanel1.add(supplier_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 80, 30));
        kGradientPanel1.add(Supplier_path, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 34, 50, 30));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 950, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void displaysAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_displaysAncestorAdded

    }//GEN-LAST:event_displaysAncestorAdded

    private void Supplier_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Supplier_tableMouseClicked
        int i=Supplier_table.getSelectedRow();
        TableModel model = Supplier_table.getModel();
        supplier_id.setText(model.getValueAt(i,0).toString());
        
        id = model.getValueAt(i,0).toString();
        name = model.getValueAt(i,1).toString();
        add = model.getValueAt(i,2).toString();
      
        contact = model.getValueAt(i,3).toString();
    }//GEN-LAST:event_Supplier_tableMouseClicked

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
        
        Insert_Supplier is = new Insert_Supplier();
        is.setVisible(true);
        Insert_Supplier.Insert_Supplier_Display.setText("ADD NEW SUPPLIER");
        

    }//GEN-LAST:event_AddMouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        Supplier_path.setText("");
        supplier_id.setText("");
        dispose();
        
    }//GEN-LAST:event_BackMouseClicked

    private void sup_listUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sup_listUpdateMouseClicked
        if(supplier_id.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "PLEASE SELECT CUSTOMER !","",JOptionPane.ERROR_MESSAGE);
           ct.Supplier();
       }else{
           Insert_Supplier is = new Insert_Supplier();
           is.setVisible(true);
           Insert_Supplier.Insert_Supplier_Display.setText("UPDATE SUPPLIER");
           ct.Supplier();
        }

    }//GEN-LAST:event_sup_listUpdateMouseClicked

    private void sup_delMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sup_delMouseClicked
      String id1 = supplier_id.getText();
      
           int opt = JOptionPane.showConfirmDialog(null, "YOU WANT TO DELETE THIS SUPPLIER ? ","",JOptionPane.YES_NO_OPTION);
            if(opt==0){
                if(JOptionPane.YES_NO_OPTION == JOptionPane.YES_OPTION ){
                    if(!Class_Supplier.DeleteSupplier(id1)){        
                    JOptionPane.showMessageDialog(null, "DELETE SUCCESSFULLY","",JOptionPane.INFORMATION_MESSAGE);
                    ct.Supplier();
                    }
                } 
            }

    }//GEN-LAST:event_sup_delMouseClicked

    private void Supplier_SearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Supplier_SearchKeyPressed
        DefaultTableModel tm = (DefaultTableModel)Supplier_table.getModel();
        String find = Supplier_Search.getText().toUpperCase();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(tm);
        Supplier_table.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(find));
    }//GEN-LAST:event_Supplier_SearchKeyPressed

    private void AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseEntered
        add_panel_supplier.setBackground(new Color(163, 235, 177));
        Add.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_AddMouseEntered

    private void sup_listUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sup_listUpdateMouseEntered
        update_panel_supplier.setBackground(new Color(163, 235, 177));
        sup_listUpdate.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_sup_listUpdateMouseEntered

    private void sup_delMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sup_delMouseEntered
       delete_panel_supplier.setBackground(new Color(163, 235, 177));
       sup_del.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_sup_delMouseEntered

    private void BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseEntered
       back_panel_supplier.setBackground(new Color(163, 235, 177));
       Back.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_BackMouseEntered

    private void AddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseExited
      add_panel_supplier.setBackground(new Color(35,215,176));
      Add.setForeground(new Color(255,255,255));

    }//GEN-LAST:event_AddMouseExited

    private void sup_listUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sup_listUpdateMouseExited
      update_panel_supplier.setBackground(new Color(51,187,255));
      sup_listUpdate.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_sup_listUpdateMouseExited

    private void sup_delMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sup_delMouseExited
       delete_panel_supplier.setBackground(new Color(255,77,77));
       sup_del.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_sup_delMouseExited

    private void BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseExited
       back_panel_supplier.setBackground(new Color(185,144,149));
       Back.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_BackMouseExited

    private void Back1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back1MouseClicked
       String path = Supplier_path.getText();
       if(supplier_id.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "PLEASE SELECT CUSTOMER !","",JOptionPane.ERROR_MESSAGE);
       }else if(path.equals("INSERT_GENERATOR")){
            Insert_Generator.supplier_id = id;
            Insert_Generator.Insert_Gen_Supplier_Name.setText(name);
            Insert_Generator.Insert_Gen_Supplier_Address.setText(add);
            //Insert_Generator.Insert_Gen_Supplier_Email.setText(email);
            Insert_Generator.Insert_Gen_Supplier_Contact.setText(contact);
            dispose();
       }else if(path.equals("INSERT_PARTS")){
            Insert_Parts.supplier_id = id;
            Insert_Parts.Insert_Parts_Supplier_name.setText(name);
            Insert_Parts.Insert_Parts_Supplier_Address.setText(add);
            //Insert_Parts.Insert_Parts_Supplier_Email.setText(email);
            Insert_Parts.Insert_Parts_Supplier_Contact.setText(contact);
            dispose();
       }else if(path.equals("VIEW_GENERATOR")){
            View_Generator.supplier_id = id;
            View_Generator.View_Gen_Supplier_Name.setText(name);
            View_Generator.View_Gen_Supplier_Address.setText(add);
            //View_Generator.View_Gen_Supplier_Email.setText(email);
            View_Generator.View_Gen_Supplier_Contact.setText(contact);
            dispose();
       }else if(path.equals("VIEW_PARTS")){
            View_Parts.supplier_id = id;
            View_Parts.View_Parts_Supplier_name.setText(name);
            View_Parts.View_Parts_Supplier_Address.setText(add);
            //View_Parts.View_Parts_Supplier_Email.setText(email);
            View_Parts.View_Parts_Supplier_Contact.setText(contact);
            dispose();
       }
    }//GEN-LAST:event_Back1MouseClicked

    private void Back1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back1MouseEntered
        // TODO add your handling code here:163, 235, 177
        Back1.setForeground(new Color(51,51,51));
         back_panel_supplier1.setBackground(new Color(163, 235, 177));
    }//GEN-LAST:event_Back1MouseEntered

    private void Back1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back1MouseExited
        // TODO add your handling code here:
        Back1.setForeground(new Color(255,255,255));
        back_panel_supplier1.setBackground(new Color(255, 102, 255));
    }//GEN-LAST:event_Back1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table_Supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Add;
    public static javax.swing.JLabel Back;
    public static javax.swing.JLabel Back1;
    private javax.swing.JTextField Supplier_Search;
    public static javax.swing.JLabel Supplier_path;
    public static javax.swing.JTable Supplier_table;
    public static javax.swing.JPanel add_panel_supplier;
    public static javax.swing.JPanel back_panel_supplier;
    public static javax.swing.JPanel back_panel_supplier1;
    public static javax.swing.JPanel delete_panel_supplier;
    public static javax.swing.JLabel displays;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    public static javax.swing.JLabel sup_del;
    public static javax.swing.JLabel sup_listUpdate;
    public static javax.swing.JLabel supplier_id;
    public static javax.swing.JPanel update_panel_supplier;
    // End of variables declaration//GEN-END:variables
}
