/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fieldpowerenterprises;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Javinez
 */
public class generator extends javax.swing.JFrame {
    PreparedStatement ps;
    ResultSet rs;
    /**
     * Creates new form generator
     */
    public generator() {
        initComponents();
    }

    //ArrayList
    
    public ArrayList<generatorClass> getFrom_generatorTbl(String query){
        ArrayList<generatorClass> getAllData = new ArrayList<>();
        
            try{
                ps = (PreparedStatement) database.getConnection().prepareStatement(query);
                rs = ps.executeQuery();
                generatorClass showAllData;
                while( rs.next() )
                {
                    showAllData = new generatorClass
                    (
                        rs.getInt("generator_id"),
                        rs.getString("phasing"),
                        rs.getString("kva"),
                        rs.getString("vac"),
                        rs.getString("supplier_price"),
                        rs.getString("seller_price"),
                        rs.getString("quantity"),
                        rs.getString("product_brandname"),
                        rs.getString("engine_model"),
                        rs.getString("engine_sn"),
                        rs.getString("alternator_sn"),
                        rs.getString("unit_type"),
                        rs.getString("starting_system"),
                        rs.getString("body_type"),
                        rs.getString("dimension"),
                        rs.getString("fuel_tank_cap"),
                        rs.getString("weight"),
                        rs.getString("frame"),
                        rs.getString("date")      
                    );
                    
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage(),"",JOptionPane.ERROR_MESSAGE);
            }
        
        return getAllData;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generatorHeaderTxt = new javax.swing.JLabel();
        generator_idTxt = new javax.swing.JLabel();
        generator_idDisplay = new javax.swing.JLabel();
        phasing_input = new javax.swing.JTextField();
        phasingTxt = new javax.swing.JLabel();
        kvaTxt = new javax.swing.JLabel();
        kva_input = new javax.swing.JTextField();
        vacTxt = new javax.swing.JLabel();
        vac_input = new javax.swing.JTextField();
        supplierpriceTxt = new javax.swing.JLabel();
        supplierprice_input = new javax.swing.JTextField();
        sellerpriceTxt = new javax.swing.JLabel();
        sellerprice_input = new javax.swing.JTextField();
        quantityTxt = new javax.swing.JLabel();
        quanity_input = new javax.swing.JTextField();
        productbrandnameTxt = new javax.swing.JLabel();
        productbrandname_input = new javax.swing.JTextField();
        enginemodelTxt = new javax.swing.JLabel();
        enginemode_input = new javax.swing.JTextField();
        engine_snTxt = new javax.swing.JLabel();
        enginesn_input = new javax.swing.JTextField();
        alternator_snTxt = new javax.swing.JLabel();
        alternator_input = new javax.swing.JTextField();
        description_input = new javax.swing.JTextField();
        unittypeTxt = new javax.swing.JLabel();
        startingsystemTxt = new javax.swing.JLabel();
        startingsystem_input = new javax.swing.JTextField();
        bodytypeTxt = new javax.swing.JLabel();
        bodytype_input = new javax.swing.JTextField();
        dimensionTxt = new javax.swing.JLabel();
        bodytype_input1 = new javax.swing.JTextField();
        fueltankcapTxt = new javax.swing.JLabel();
        fueltankcap_input = new javax.swing.JTextField();
        weightTxt = new javax.swing.JLabel();
        weight_input = new javax.swing.JTextField();
        frametTxt = new javax.swing.JLabel();
        frame_input = new javax.swing.JTextField();
        dateTxt = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        showImg = new javax.swing.JLabel();
        upload = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        generatorHeaderTxt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        generatorHeaderTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        generatorHeaderTxt.setText("Generator");

        generator_idTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        generator_idTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        generator_idTxt.setText("ID");

        generator_idDisplay.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        generator_idDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        generator_idDisplay.setText("None");

        phasing_input.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        phasing_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phasing_input.setToolTipText("");

        phasingTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        phasingTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phasingTxt.setText("Phasing");

        kvaTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        kvaTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kvaTxt.setText("Kva");

        kva_input.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        kva_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kva_input.setToolTipText("");

        vacTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        vacTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vacTxt.setText("Vac");

        vac_input.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        vac_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vac_input.setToolTipText("");

        supplierpriceTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        supplierpriceTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        supplierpriceTxt.setText("Supplier Price");

        supplierprice_input.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        supplierprice_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        supplierprice_input.setToolTipText("");

        sellerpriceTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sellerpriceTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sellerpriceTxt.setText("Seller Price");

        sellerprice_input.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        sellerprice_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sellerprice_input.setToolTipText("");

        quantityTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        quantityTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantityTxt.setText("Quantity");

        quanity_input.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        quanity_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quanity_input.setToolTipText("");

        productbrandnameTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        productbrandnameTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productbrandnameTxt.setText("Product Brandname");

        productbrandname_input.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        productbrandname_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        productbrandname_input.setToolTipText("");

        enginemodelTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        enginemodelTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enginemodelTxt.setText("Engine");

        enginemode_input.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        enginemode_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        enginemode_input.setToolTipText("");

        engine_snTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        engine_snTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        engine_snTxt.setText("Engine Serial Number");

        enginesn_input.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        enginesn_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        enginesn_input.setToolTipText("");

        alternator_snTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        alternator_snTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alternator_snTxt.setText("Alternator Serial Number");

        alternator_input.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        alternator_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        alternator_input.setToolTipText("");

        description_input.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        description_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        description_input.setToolTipText("");
        description_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                description_inputActionPerformed(evt);
            }
        });

        unittypeTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        unittypeTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unittypeTxt.setText("Unit Type");

        startingsystemTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        startingsystemTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        startingsystemTxt.setText("Starting System");

        startingsystem_input.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        startingsystem_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        startingsystem_input.setToolTipText("");

        bodytypeTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bodytypeTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bodytypeTxt.setText("Body Type");

        bodytype_input.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bodytype_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bodytype_input.setToolTipText("");

        dimensionTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        dimensionTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dimensionTxt.setText("Dimension");

        bodytype_input1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bodytype_input1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bodytype_input1.setToolTipText("");
        bodytype_input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodytype_input1ActionPerformed(evt);
            }
        });

        fueltankcapTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        fueltankcapTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fueltankcapTxt.setText("Fuel Tank Capacity");

        fueltankcap_input.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fueltankcap_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fueltankcap_input.setToolTipText("");
        fueltankcap_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fueltankcap_inputActionPerformed(evt);
            }
        });

        weightTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        weightTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        weightTxt.setText("Weight");

        weight_input.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        weight_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        weight_input.setToolTipText("");
        weight_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weight_inputActionPerformed(evt);
            }
        });

        frametTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        frametTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        frametTxt.setText("Frame");

        frame_input.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        frame_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        frame_input.setToolTipText("");
        frame_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frame_inputActionPerformed(evt);
            }
        });

        dateTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        dateTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateTxt.setText("Date");

        dateChooserCombo1.setCalendarPreferredSize(new java.awt.Dimension(400, 200));

        showImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        upload.setText("Choose");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(generatorHeaderTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sellerpriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vacTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kvaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phasingTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generator_idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(vac_input, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(kva_input, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(phasing_input, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(generator_idDisplay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                    .addComponent(sellerprice_input, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productbrandnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enginemodelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(engine_snTxt))
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplierpriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(enginemode_input, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addComponent(productbrandname_input, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(quanity_input, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(supplierprice_input, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(enginesn_input, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alternator_snTxt)
                            .addComponent(unittypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(bodytypeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(startingsystemTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(alternator_input, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(description_input, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(startingsystem_input, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bodytype_input, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(weightTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(weight_input, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fueltankcapTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fueltankcap_input, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dateTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(frametTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(frame_input, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dimensionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bodytype_input1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(showImg, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(upload)
                        .addGap(95, 95, 95))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(generatorHeaderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showImg, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(upload))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(supplierpriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(supplierprice_input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(quanity_input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productbrandnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(productbrandname_input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(startingsystemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(startingsystem_input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(frametTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(description_input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(alternator_snTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(unittypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(alternator_input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fueltankcapTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fueltankcap_input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(weightTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(weight_input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(frame_input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(enginemode_input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bodytypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bodytype_input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dateChooserCombo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(engine_snTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(enginesn_input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dimensionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bodytype_input1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(generator_idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(phasingTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(kvaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(vacTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sellerpriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sellerprice_input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(generator_idDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(phasing_input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(kva_input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(vac_input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(enginemodelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(46, 46, 46))))
                .addGap(421, 448, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bodytype_input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodytype_input1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bodytype_input1ActionPerformed

    private void fueltankcap_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fueltankcap_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fueltankcap_inputActionPerformed

    private void weight_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weight_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weight_inputActionPerformed

    private void frame_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frame_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frame_inputActionPerformed

    private void description_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_description_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_description_inputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new generator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alternator_input;
    private javax.swing.JLabel alternator_snTxt;
    private javax.swing.JLabel bodytypeTxt;
    private javax.swing.JTextField bodytype_input;
    private javax.swing.JTextField bodytype_input1;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JLabel dateTxt;
    private javax.swing.JTextField description_input;
    private javax.swing.JLabel dimensionTxt;
    private javax.swing.JLabel engine_snTxt;
    private javax.swing.JTextField enginemode_input;
    private javax.swing.JLabel enginemodelTxt;
    private javax.swing.JTextField enginesn_input;
    private javax.swing.JTextField frame_input;
    private javax.swing.JLabel frametTxt;
    private javax.swing.JLabel fueltankcapTxt;
    private javax.swing.JTextField fueltankcap_input;
    private javax.swing.JLabel generatorHeaderTxt;
    private javax.swing.JLabel generator_idDisplay;
    private javax.swing.JLabel generator_idTxt;
    private javax.swing.JLabel kvaTxt;
    private javax.swing.JTextField kva_input;
    private javax.swing.JLabel phasingTxt;
    private javax.swing.JTextField phasing_input;
    private javax.swing.JLabel productbrandnameTxt;
    private javax.swing.JTextField productbrandname_input;
    private javax.swing.JTextField quanity_input;
    private javax.swing.JLabel quantityTxt;
    private javax.swing.JLabel sellerpriceTxt;
    private javax.swing.JTextField sellerprice_input;
    private javax.swing.JLabel showImg;
    private javax.swing.JLabel startingsystemTxt;
    private javax.swing.JTextField startingsystem_input;
    private javax.swing.JLabel supplierpriceTxt;
    private javax.swing.JTextField supplierprice_input;
    private javax.swing.JLabel unittypeTxt;
    private javax.swing.JButton upload;
    private javax.swing.JLabel vacTxt;
    private javax.swing.JTextField vac_input;
    private javax.swing.JLabel weightTxt;
    private javax.swing.JTextField weight_input;
    // End of variables declaration//GEN-END:variables
}
